// Reviewed against complete pinned native descriptions, including ritual outcomes.
// Each row describes casting imagery. Saves, delayed triggers and unknown choices
// remain rules; symbolic objects do not select a creature form or destination.
const ART = {
 eyes:'eyes.01.dark_green.single', manyEyes:'eyes.01.dark_green.many',
 chain:'markers.chain.standard.complete.02.red', strands:'energy_strands.complete.blue.01',
 link:'energy_strands.range.standard.purple.01', field:'energy_field',
 leaf:'swirling_leaves.complete.01.green', roots:'entangle.02.complete.02.green',
 plants:'plant_growth.03.round.4x4.complete.greenyellow', smoke:'smoke.plumes.01.grey',
 fog:'fog_cloud', dust:'particles.outward', inward:'particles.inward',
 stars:'twinkling_stars', gem:'ioun_stones.01.pink.protection', insight:'ioun_stones.01.blue.insight',
 glint:'glint', shimmer:'shimmer.01.blue', shield:'shield.01.complete.01.blue',
 rune:'icon.runes.orange', script:'icon.runes02.orange', mind:'icon.runes03.orange',
 ward:'ward.rune.yellow.01', holy:'ward.star.yellow.01', heart:'icon.heart.pink',
 fear:'icon.fear.dark_purple', horror:'icon.horror.purple', skull:'icon.skull.purple',
 mute:'icon.mute.dark_red', poison:'icon.poison.dark_green', cracked:'icon.shield_cracked.purple',
 die:'icosahedron.roll.blue', clock:'icosahedron.rune.above.blueyellow',
 music:'music_notations', note:'icon.music_note.blue', sound:'soundwave.02', wave:'soundwave.01',
 water:'liquid.splash.blue', glob:'liquid.blob.blue', blood:'liquid.splash02.red',
 bubble:'bubble.001.001.complete.blue', winds:'wind_lines.01.01.white',
 gust:'gust_of_wind', windWall:'wind_wall.300x100',
 rock:'falling_rocks.top.1x1.grey', cracks:'ground_cracks',
 ice:'ice_spikes.radial', snow:'sleet_storm', fire:'flames.04.complete',
 fireLoop:'flames.04.loop', feather:'swirling_feathers.outburst.01.textured',
 palm:'arcane_hand.blue', fists:'unarmed_strike.magical.01.blue',
 claw:'claws', sword:'spiritual_weapon.longsword', staff:'quarterstaff.melee',
 tool:'wrench.melee.01.white', portal:'portals.horizontal.ring',
 light:'template_circle.aura.01.complete.large.bluepurple',
 dark:'darkness', soul:'spirit_guardians', void:'arms_of_hadar',
 moon:'celestial_bodies.planet.no_atmo.03.grey', sun:'flaming_sphere',
 vortex:'template_circle.vortex.loop', web:'web', beam:'energy_beam',
 fireCone:'breath_weapons.fire.cone.orange.01', waterCone:'water_splash.cone.01.blue',
 fireWall:'wall_of_fire.300x100.yellow', forceWall:'wall_of_force.vertical.grey',
 iceLine:'template_line.ice.01.blue',
};
const art = value => ART[value] ?? value;
const B=(slot,asset,label,options={})=>({type:'body',slot,asset:art(asset),label,options});
const S=(slot,asset,label,options={})=>B(slot,asset,label,{subject:'source',...options});
const A=(slot,asset,label,options={})=>({type:'area',slot,asset:art(asset),label,options});
const T=(asset,label,options={})=>({type:'travel',slot:'bolt',asset:art(asset),label,options});
const F=(asset,label,options={})=>({type:'fan',slot:'bolt',asset:art(asset),label,options});
const D=(label,options={})=>({type:'copy',label,options});
const P=(motion,label,subject='source')=>({type:'pose',motion,label,subject});
const E=(label,theme,nodes,options={})=>({label,theme,nodes,symbolic:true,castingOnly:true,...options});

const REVIEWED = {
 'reinforced-rations':E('Ration preservation','ward',[S('hit','water','Food and drink'),S('aura','shield','Preservation invocation')]),
 'rejuvenating-flames':E('Healing flame gout','fire',[A('area','fireCone','Healing and burning flame')],{nativeArea:true,symbolic:false,castingOnly:false}),
 'release-the-ego-to-restore-the-soul':E('Dance invocation','sonic',[S('hit','music','Dance music'),S('aura','sound','Shared rhythm'),P('spin','Dance turn')]),
 remake:E('Object reassembly','transform',[B('hit','inward','Remnants gather'),B('aura','shimmer','Object reassembly',{tween:[['scale.x',.3,1,2500],['scale.y',.3,1,2500]]})]),
 'remake-physiology':E('Mismatched anatomy','transform',[B('hit','claw','Altered limbs',{scale:.7,offsetY:.2}),B('aura','manyEyes','Mismatched eyes',{scale:.65,offsetY:-.3})]),
 'remember-the-lost':E('Memories of the lost','mind',[S('cast','sound','Victims named'),A('area','skull','Memories of the dead'),A('aura','mind','Grievance visions',{scale:.7})],{nativeArea:true,castingOnly:false}),
 'rend-magic':E('Magical arm attack','force',[S('cast','strands','Arm magic',{offsetX:.25,scale:.7}),B('hit','palm','Magical hand contact'),B('aura','cracked','Magic vulnerability',{scale:.5})],{castingOnly:false}),
 'repelling-pulse':E('Telekinetic pulse','force',[A('area','field','Outward telekinetic pulse',{tween:[['scale.x',.2,1,1500],['scale.y',.2,1,1500]]})],{nativeArea:true,castingOnly:false}),
 replicate:E('Illusory double','illusion',[B('hit','shimmer','Double formation',{offsetX:1}),D('Illusory double',{copies:1,copySpread:0,offsetX:1,opacity:.7})]),
 repulsion:E('Approach barrier','force',[A('area','field','Repulsion boundary',{opacity:.5}),S('hit','palm','Outward barrier')],{delivery:'emanation',previewArea:{type:'emanation',value:40},nativeArea:true}),
 'resolute-obliteration':E('Object aging invocation','void',[S('hit','skull','Void invocation'),S('aura','dust','Object aging intent',{saturation:-1})]),
 'resplendent-mansion':E('Mansion construction','transform',[S('hit','script','Mansion plan',{offsetY:-.35}),S('aura','shimmer','Architectural manifestation',{scale:2})]),
 'rest-eternal':E('Afterlife sequestration','spirit',[B('hit','skull','Departed subject'),B('aura','ward','Afterlife invocation')]),
 'restorative-moment':E('Restorative time threads','time',[B('hit','clock','Day passage'),B('aura','strands','Restorative time threads')]),
 'restore-ground':E('Natural terrain restoration','plant',[A('hit','cracks','Civilized ground loosens'),A('area','plants','Natural growth'),A('aura','leaf','Healthy plants')],{nativeArea:true,castingOnly:false}),
 'restraining-chains':E('Steel chain restraint','metal',[B('hit','chain','Steel chain',{below:true,offsetY:.15}),B('aura','chain','Fettered limbs',{scale:1.2})]),
 resurrect:E('Soul recall invocation','spirit',[B('hit','skull','Departed body',{scale:.5}),B('aura','soul','Soul recall invocation',{opacity:.45})]),
 'retreat-among-the-rains':E('Retraining mindscape','mind',[S('hit','mind','Mindscape concentration'),S('aura','insight','Retraining invocation',{offsetY:-.35})]),
 retrocognition:E('Past emotional impressions','mind',[S('hit','mind','Past impressions',{offsetY:-.3}),S('aura','clock','Earlier time echoes',{offsetY:-.5,scale:.6})]),
 'return-to-essence':E('Ward energy reclamation','force',[B('hit','ward','Ward unweaving',{scaleOut:.2,scaleOutDuration:2500}),T('link','Ward energy draws inward',{travelOrigin:'target'}),S('aura','inward','Reclaimed essence')]),
 'revealing-light':E('Revealing motes','light',[A('area','stars','Revealing light motes'),A('aura','glint','Heatless revealing light')],{nativeArea:true,symbolic:false,castingOnly:false}),
 'revel-in-retribution':E('Reactive combat readiness','time',[S('hit','clock','Time seems slower'),S('aura','sword','Reactive weapon readiness',{scale:.65,offsetX:.4})]),
 'rewinding-step':E('Temporal location anchor','time',[S('hit','clock','Temporal anchor',{below:true}),S('aura','ward','Return location marked',{below:true,scale:.65})]),
 'rewrite-memory':E('Memory editing','mind',[B('hit','mind','Memory inscription',{offsetY:-.3}),B('aura','shimmer','Memory edits',{offsetY:-.3,scale:.7})]),
 'rewrite-possibility':E('Fate guidance','divination',[B('hit','eyes','Possible futures',{offsetY:-.3,scale:.5}),B('aura','die','Fate guidance',{offsetY:-.5,scale:.6})]),
 'rigid-form':E('Wooden rigidity','plant',[S('hit','leaf','Wood rigidity'),S('aura','shield','Shape protection')]),
 'rime-slick':E('Chill wind and ice','cold',[A('hit','winds','Chill wind'),A('area','ice','Surface ice')],{nativeArea:true,castingOnly:false}),
 'ring-of-truth':E('Truth boundary','divination',[A('area','ward','Truth boundary'),A('aura','note','Bell attunement',{scale:.5,opacity:.45})],{nativeArea:true}),
 'rip-the-spirit':E('Spirit separation','void',[B('hit','soul','Spirit separation'),D('Spirit silhouette',{copies:1,copySpread:0,offsetY:-.35,opacity:.35}),B('aura','skull','Void severance',{scale:.6})],{castingOnly:false}),
 'rising-surf':E('Surfing wave','water',[S('hit','water','Rising wave',{below:true}),P('levitate','Surf lift'),S('aura','glob','Water beneath feet',{below:true,offsetY:.3})],{castingOnly:false}),
 'rite-of-cleansing-flame':E('Phoenix invocation','spirit',[S('hit','feather','Phoenix patron'),S('aura','fire','Cleansing invocation',{opacity:.5})]),
 'rite-of-repatriation':E('Spirit apology','spirit',[B('hit','soul','Local spirits',{opacity:.5}),B('aura','script','Object repatriation')]),
 'rite-of-the-red-star':E('Doorway invocation','teleport',[S('hit','sound','Doorway chanting'),S('aura','rune','Red Star invocation',{offsetY:-.4})]),
 'ritual-obstruction':E('Ritual feedback zone','ward',[A('area','strands','Ritual feedback'),A('aura','cracked','Obstructed ritual marks')],{nativeArea:true}),
 'rolling-boulders':E('Earth following invocation','earth',[S('hit','rock','Earth invocation',{below:true}),S('aura','cracks','Stones called',{below:true})]),
 'rope-trick':E('Rising rope','teleport',[B('hit','strands','Rope rises',{scale:.65,tween:[['scale.y',.3,1.8,2500]],offsetY:-.35}),B('aura','shimmer','Hidden extradimensional opening',{scale:.4,offsetY:-1})]),
 'rouse-skeletons':E('Grasping skeletons','void',[A('area','palm','Grasping skeletal hands'),A('aura','skull','Skeletal forms',{scale:.8})],{nativeArea:true,castingOnly:false}),
 'rousing-splash':E('Cold water splash','water',[B('hit','water','Water on head',{offsetY:-.3}),B('aura','heart','Temporary vigor',{scale:.5})],{symbolic:false}),
 'rubble-step':E('Rubble trail preparation','earth',[B('hit','rock','Earthen trail ready',{below:true,scale:.65}),B('aura','dust','Rubble at feet',{below:true,scale:.75})]),
 'rune-trap':E('Stored spell rune','ward',[B('hit','ward','Trap rune'),B('aura','gem','Bound spell potential',{scale:.5})]),
 'rusting-grasp':E('Metal corrosion','metal',[B('hit','dust','Rust spreads',{maskToken:true,tintEnabled:true,colorize:true,tint:'#a05c33'}),B('aura','cracked','Corroded metal',{scale:.65})],{castingOnly:false}),
 'sacred-covenant':E('Sacred pact','ward',[T('link','Covenant bond'),B('hit','holy','Sacred oath'),B('aura','heart','Shared survival pact',{scale:.55})]),
 'safeguard-secret':E('Secret protection','mind',[B('hit','script','Protected knowledge',{scale:.6,offsetY:-.3}),B('aura','shield','Secret defense',{scale:.85,offsetY:-.25})]),
 'sages-curse':E('Distracting minutiae','mind',[B('hit','script','Distracting knowledge',{offsetY:-.35}),B('aura','dizzy_stars','Second guessing',{offsetY:-.5,scale:.65})]),
 'sand-form':E('Sand body','earth',[B('hit','dust','Sand aspects',{maskToken:true}),B('aura','shield','Sand resilience',{opacity:.5})]),
 'sanguine-transference':E('Blood and soul transfer','blood',[S('cast','blood','Body diffuses into blood'),T('link','Blood and soul transference',{tintEnabled:true,colorize:true,tint:'#b22538'}),B('hit','blood','Body reforms'),B('aura','shimmer','Reformed body')],{castingOnly:false}),
 'sawtooth-terrain':E('Serrated mantis limbs','metal',[A('area','claw','Serrated limbs'),A('aura','blood','Cutting terrain',{opacity:.45})],{nativeArea:true,castingOnly:false}),
 'scholarly-recollection':E('Recollection prayer','divination',[S('hit','script','Gathered thoughts',{offsetY:-.3}),S('aura','insight','Scholarly insight',{offsetY:-.5,scale:.6})]),
 'scouring-pulse':E('Scouring vitality','vitality',[A('area','light','Vitality cylinder'),A('aura','glint','Heatless light')],{nativeArea:true,castingOnly:false}),
 'scouring-sand':E('Scouring grit','earth',[A('area','dust','Scouring grit',{tintEnabled:true,colorize:true,tint:'#c7a778'}),A('aura','winds','Grit blast')],{nativeArea:true,symbolic:false}),
 'scouting-eye':E('Floating eye sensor','divination',[S('hit','eyes','Floating scouting eye',{scale:.3,offsetY:-.5}),S('aura','shimmer','Invisible sensor',{scale:.35,offsetY:-.5})]),
 'sculpt-appearance':E('Clay facial sculpting','transform',[B('hit','palm','Face sculpting',{scale:.65,offsetY:-.25}),B('aura','shimmer','Pigment and clay',{scale:.7,offsetY:-.25})]),
 'sea-of-thought':E('Semi-solid thought','mind',[A('area','glob','Sloshing thought',{opacity:.65}),A('aura','mind','Thought torrent',{scale:.6})],{nativeArea:true}),
 'sea-surge':E('Rushing water wall','water',[A('area','glob','Surging water segments'),S('hit','water','Surface slap')],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:15},castingOnly:false}),
 'seal-fate':E('Death curse','void',[B('hit','skull','Fated death mark',{offsetY:-.4,scale:.5}),B('aura','ward','Fate seal',{scale:.65})]),
 'secret-chest':E('Ethereal container','teleport',[B('hit','shimmer','Container turns ethereal',{maskToken:true}),B('aura','portal','Ethereal banishment',{scaleOut:.2,scaleOutDuration:2500})]),
 'secret-page':E('Replacement text','illusion',[B('hit','script','Replacement text',{scale:.65}),B('aura','shimmer','Concealed writing',{scale:.75})]),
 'secure-siege-weapons':E('Siege weapon warding','ward',[S('hit','shield','Siege fortification invocation'),S('aura','ward','Enemy operation ward')]),
 'seed-of-mercy':E('Injured bird tending','healing',[S('hit','feather','Injured bird'),S('aura','heart','Merciful tending',{scale:.6})]),
 'seize-identity':E('Voice and identity seizure','mind',[B('hit','mute','Voice seized',{offsetY:-.3}),T('link','Identity draws inward',{travelOrigin:'target'}),S('aura','shimmer','Borrowed appearance')]),
 'seize-soul':E('Soul containment','spirit',[B('hit','soul','Soul gathers'),B('aura','gem','Soul vessel',{scale:.55})]),
 separation:E('Fate separation invocation','ward',[B('hit','die','Separate fates',{scale:.6}),B('aura','palm','Separation petition')]),
 'sepulchral-mask':E('Funerary mask','mind',[S('hit','skull','Funerary mask',{scale:.55,offsetY:-.3}),A('area','fear','Regret and sin',{opacity:.5})],{nativeArea:true,castingOnly:false}),
 serrate:E('Jagged weapon edges','metal',[B('hit','sword','Weapon edge',{offsetX:.35,scale:.7}),B('aura','claw','Jagged serrations',{offsetX:.35,scale:.6})]),
 'shadow-blast':E('Shadow substance blast','shadow',[A('area','dark','Shadow substance')],{delivery:'burst',previewArea:{type:'burst',value:15},nativeArea:true,castingOnly:false}),
 'shadow-double':E('Shadow sculpting invocation','shadow',[B('hit','dark','Netherworld material',{scale:.85}),B('aura','palm','Double sculpting')]),
 'shadow-illusion':E('Shadow illusion shaping','shadow',[S('hit','dark','Shadow substance'),S('aura','shimmer','Unspecified illusion form',{scale:1.4})]),
 'shadows-web':E('Grasping darkness','void',[A('area','void','Grasping darkness'),A('aura','dark','Void web')],{nativeArea:true,castingOnly:false}),
 'shaken-confidence':E('Mockery and doubt','mind',[S('cast','sound','Mocking voice'),B('hit','fear','Shaken confidence',{offsetY:-.3,scale:.65}),B('aura','die','Doubtful fortune',{scale:.45})]),
 'shape-wood':E('Wood shaping','plant',[B('hit','leaf','Wood material'),B('aura','palm','Rough shaping',{scale:.7})]),
 'share-burden':E('Shared emotional burden','mind',[T('link','Ally burden',{travelOrigin:'target'}),S('hit','heart','Shared pain'),B('aura','shield','Emotional support')]),
 'share-life':E('Linked life essence','healing',[T('link','Life essence bond'),B('hit','heart','Shared life'),B('aura','strands','Life link')]),
 'shared-invisibility':E('Shared invisible veil','illusion',[B('hit','shimmer','Shared invisible veil',{maskToken:true}),D('Invisible silhouettes',{copies:1,copySpread:0,opacity:.3,tween:[['alpha',.3,0,2500]]})],{delivery:'target'}),
 'shared-nightmare':E('Nightmare exchange','mind',[T('link','Merged minds'),S('hit','horror','Shared distress'),B('aura','fear','Nightmare visions',{offsetY:-.3})]),
 'shatter-mind':E('Telepathic assault','mind',[F('mind','Assailing mental symbols',{fanCount:5})],{delivery:'cone',nativeArea:true}),
 'shattering-gem':E('Protective orbiting gem','ward',[B('hit','gem','Floating protective gem'),B('aura','shield','Gem defense',{opacity:.5})]),
 'shielding-formation':E('Force shield formation','ward',[A('area','shield','Force shield formation'),A('aura','strands','Linked protection',{opacity:.5})],{nativeArea:true}),
 'shift-perspective':E('Thrown object sight','divination',[S('cast','palm','Object toss'),B('hit','eyes','Object perspective',{scale:.4,offsetY:-.3})]),
 shillelagh:E('Leafy staff empowerment','plant',[B('hit','roots','Weapon vines',{offsetX:.3,scale:.7}),B('aura','leaf','Weapon leaves',{offsetX:.3,scale:.8})],{symbolic:false}),
 'shining-starlight-attack':E('Constellation invocation','light',[S('hit','stars','Constellation above head',{offsetY:-.65}),S('aura','sword','Sentinel weapon',{offsetX:.35,scale:.65})]),
 shipwreck:E('Vessel wrenching','force',[B('hit','strands','Vessel wrenches',{tween:[['scale.x',.6,1.5,2000]]}),B('aura','cracked','Structural fracture',{scale:.65})]),
 shockwave:E('Earth shockwave','earth',[F('cracks','Ground ripple',{fanCount:5,below:true})],{nativeArea:true,castingOnly:false}),
 'show-the-path':E('Fitting future guidance','divination',[B('hit','insight','Future insight',{offsetY:-.3,scale:.6}),B('aura','die','Possible outcome',{scale:.55})]),
 'shroud-of-night':E('Darkened eyes','shadow',[B('hit','eyes','Eyes veiled',{offsetY:-.3,scale:.5}),B('aura','dark','Murky eye shroud',{offsetY:-.3,scale:.7})]),
 'shroud-of-the-mantis':E('Crimson cloak','illusion',[S('hit','shimmer','Crimson cloak',{tintEnabled:true,colorize:true,tint:'#ae2438',maskToken:true}),D('Veiled silhouette',{copies:1,copySpread:0,opacity:.25,tween:[['alpha',.25,0,2200]]})]),
 'shroud-of-the-provinces':E('Dewdrop fog invocation','water',[S('hit','glob','Collected dewdrops',{scale:.5}),S('aura','fog','Fog essence invocation')]),
 'sign-of-conviction':E('Religious force sign','force',[S('cast','holy','Religious sign',{offsetY:-.65,scale:.7}),T('beam','Force sign blast'),B('hit','strands','Directed energy')],{castingOnly:false}),
 'skeletal-lancers':E('Skeleton spear summons','void',[S('hit','skull','Skeletons called'),S('aura','spiritual_weapon.spear','Bony spear armament',{scale:.75})]),
 'skeleton-army':E('Skeletal hulks arrive','void',[A('area','palm','Bony hands rise'),A('aura','skull','Skeletal legion')],{delivery:'emanation',previewArea:{type:'emanation',value:20},nativeArea:true,castingOnly:false}),
 'sky-signs':E('Atmospheric message invocation','wind',[S('hit','fog','Atmospheric medium',{offsetY:-.7,scale:1.5}),S('aura','script','Message symbols',{offsetY:-.7})]),
 'skyglass-prison':E('Glass air cage','wind',[B('hit','bubble','Hardened air enclosure',{scale:1.4}),B('aura','shimmer','Glass cage',{scale:1.15})]),
 sleep:E('Drowsy sleep','mind',[A('area','sleep','Drowsiness'),A('aura','moon','Sleep symbol',{scale:.5,opacity:.4})],{nativeArea:true}),
 'sleepless-season':E('Sleepless curse invocation','mind',[S('hit','gem','Amethyst pendant'),S('aura','eyes','Restless invocation',{offsetY:-.3})]),
 'slough-skin':E('Harmless skin shedding','transform',[S('hit','shimmer','New skin',{maskToken:true}),S('aura','dust','Skin sheds',{tween:[['position.y',0,.6,2600]],opacity:.5})]),
 'soft-landing':E('Buoyant landing field','force',[A('area','field','Buoyant field',{tween:[['scale.y',.5,1,2000]],opacity:.65}),A('aura','feather','Gentle landing',{opacity:.55})],{nativeArea:true}),
 'song-of-silver':E('Silver song performance','sonic',[S('hit','music','Song performance'),S('aura','sound','Silver song',{tintEnabled:true,colorize:true,tint:'#cfd6e3'})]),
 'soothing-words':E('Soothing speech','mind',[S('cast','sound','Calm voice',{scale:.7}),B('hit','heart','Soothing words',{scale:.6}),B('aura','shield','Emotional resilience')]),
 'speak-with-magic':E('Ethereal magical speech','sonic',[S('hit','sound','Ethereal voice'),S('aura','rune','Magical language',{scale:.6,offsetY:-.3})]),
 'speak-with-plants':E('Plant communion','plant',[S('hit','sound','Questions to plants'),S('aura','leaf','Plant conversation')]),
 'speak-with-water':E('Primal water speech','water',[S('hit','sound','Primal water sounds'),S('aura','water','Water spirit communion')]),
 'spell-riposte':E('Counterspell reflection','ward',[S('hit','shield','Counterspell parry'),S('aura','strands','Reflected spell threads',{tween:[['scale.x',1,.3,1600]]})]),
 'spell-turning':E('Spell reflection ward','ward',[S('hit','shield','Reflection ward'),S('aura','shimmer','Reflective surface',{opacity:.6})]),
 spellsurge:E('Surging magic aura','force',[A('area','strands','Surging magic'),A('aura','field','Aura of raw power',{opacity:.55})],{nativeArea:true}),
 spellwrack:E('Spell energy curse','force',[B('hit','rune','Spellwrack curse',{scale:.65}),B('aura','strands','Unstable spell energy',{opacity:.6})]),
 'spider-sting':E('Venomous sting','poison',[B('hit','claw','Piercing sting',{scale:.5}),B('aura','poison','Spider venom',{scale:.6})],{castingOnly:false}),
 'spinning-staff':E('Staff twirling strikes','metal',[S('cast','staff','Staff flourish',{tween:[['rotation',0,360,1800]]}),P('spin','Twirling gesture'),B('hit','staff','Staff strikes'),S('aura','strands','Spellstrike charge')],{castingOnly:false}),
 'spirit-blast':E('Ethereal spirit assault','spirit',[B('hit','soul','Spirit blast'),B('aura','strands','Ethereal energy')],{castingOnly:false}),
 'spirit-object':E('Object animation','transform',[B('hit','shimmer','Object awakens'),D('Animated object silhouette',{copies:1,copySpread:0,opacity:.8}),B('aura','winds','Locomotion ready',{below:true,scale:.65})]),
 'spiritual-attunement':E('Outer Sphere attunement','spirit',[S('hit','soul','Spirit connects'),S('aura','shield','Planar protection')]),
 'spiritual-epidemic':E('Contagious spirit curse','void',[B('hit','skull','Spirit curse',{scale:.55}),B('aura','strands','Contagion held',{opacity:.6})]),
 'spiritual-guardian':E('Force guardian invocation','spirit',[S('hit','soul','Guardian called'),S('aura','shield','Guardian protection intent',{scale:.65})]),
 'split-shadow':E('Mirror shadow shaping','shadow',[B('hit','shimmer','Mirror surface'),B('aura','dark','Shadow shaping',{scale:.85})]),
 'sprawling-tunnels':E('Tunnel map inscription','earth',[S('hit','script','Tunnel map',{below:true}),S('aura','glob','Ink on map',{below:true,scale:.65,tintEnabled:true,colorize:true,tint:'#2d283b'})]),
 'stagnate-time':E('Thickened time stream','time',[A('area','clock','Temporal pins'),A('aura','field','Slow time stream',{opacity:.45,playbackRate:.65})],{nativeArea:true}),
 'stars-of-another-sky':E('Astral River of Souls','spirit',[A('area','stars','Astral sky'),A('aura','soul','River of Souls',{opacity:.5})],{nativeArea:true}),
 stasis:E('Congealed time','time',[B('hit','clock','Time congeals',{offsetY:-.35,scale:.6}),B('aura','bubble','Temporal enclosure',{opacity:.7})]),
 statuette:E('Object miniaturization invocation','transform',[B('hit','palm','Miniature shaping'),B('aura','shimmer','Statuette invocation',{scale:.6})]),
 'steal-shadow':E('Shadow theft','shadow',[B('hit','dark','Shadow loosens',{below:true}),T('link','Shadow draws to hand',{travelOrigin:'target'}),S('aura','palm','Shadow grasp',{scale:.65,offsetX:.25})]),
 'steal-voice':E('Voice theft','sonic',[B('hit','mute','Voice silenced',{offsetY:-.25,scale:.6}),T('link','Stolen voice',{travelOrigin:'target'}),S('aura','sound','Borrowed voice',{scale:.65})]),
 'steel-fortifications':E('Metal fortification beams','metal',[S('hit','spiritual_weapon.spear','Angled metal beams',{rotation:45,scale:1.4}),S('aura','shield','Cover structure intent')]),
 'still-life-storage':E('Still life painting','illusion',[S('hit','script','Canvas composition'),S('aura','shimmer','Objects painted into scene')]),
 'stoke-the-heart':E('Fervor empowerment','mind',[B('hit','heart','Heart stoked',{scale:.65}),B('aura','sword','Empowered blows ready',{scale:.6,offsetX:.35})]),
 'stop-heart':E('Heart squeeze','void',[B('hit','heart','Heart grasp',{scale:.6,tween:[['scale.x',1,.4,1800],['scale.y',1,.4,1800]]}),B('aura','palm','Cruel squeeze',{scale:.8})],{castingOnly:false}),
 'store-time':E('Stored reaction time','time',[S('hit','clock','Time stored',{scale:.7}),S('aura','gem','Reaction reserve',{scale:.5})]),
 stormburst:E('Lightning and wind storm','electricity',[S('cast','sound','Thunder voice'),A('area','static_electricity','Localized lightning'),A('aura','winds','Storm wind')],{nativeArea:true,castingOnly:false,symbolic:false}),
 'string-of-fate':E('Shared fate thread','divination',[T('link','Fate thread'),B('hit','die','Shared fortune',{scale:.6}),S('aura','heart','Cherished bond',{scale:.55})]),
 'stumbling-curse':E('Haphazard movement curse','mind',[B('hit','rune','Trajectory curse',{below:true,scale:.65}),B('aura','dizzy_stars','Unsteady direction',{offsetY:.3,scale:.7})]),
 'subconscious-suggestion':E('Subconscious directive','mind',[B('hit','script','Directive planted',{offsetY:-.3,scale:.55}),B('aura','mind','Subconscious trigger',{offsetY:-.3,scale:.85})]),
 'sudden-shift':E('Veiled evasive step','illusion',[S('hit','shimmer','Veiling shimmer'),P('dodge','Evasive step'),S('aura','fog','Concealment veil',{opacity:.6})],{castingOnly:false}),
 'sudden-transposition':E('Teleportation wrench','teleport',[B('hit','portal','Teleportation potential'),B('aura','strands','Spatial wrench')],{delivery:'target'}),
 suffocate:E('Breath withdrawal','wind',[B('hit','winds','Breath draws out',{offsetY:-.2,tween:[['scale.x',1.2,.3,2300]]}),B('aura','mute','Breath deprivation',{scale:.5,offsetY:-.15})],{castingOnly:false}),
 'summerland-spell':E('Weather tempering invocation','wind',[S('hit','sun','Temperate weather intent',{scale:.55,offsetY:-.4}),S('aura','winds','Weather invocation')]),
 'suns-fury':E('Glowing weapon flame','fire',[B('hit','fire','Weapon flame',{offsetX:.35,scale:.7}),B('aura','glint','Torch brightness',{offsetX:.35,scale:.7})],{symbolic:false}),
 sunburst:E('Searing sunlight globe','light',[A('area','sun','Sunlight globe'),A('hit','glint','Searing sunlight'),A('aura','fire','Solar heat',{opacity:.55})],{nativeArea:true,castingOnly:false}),
 'supreme-connection':E('Vine entity petition','plant',[S('hit','roots','Vines and branches'),S('aura','eyes','Entity petition',{scale:.55,offsetY:-.2})]),
 'suspended-retribution':E('Suspended doom omen','mind',[B('hit','sword','Suspended sword omen',{offsetY:-.8,rotation:90,scale:.8}),B('aura','skull','Doom warning',{offsetY:-.45,scale:.35})]),
 'swallow-light':E('Consumed magical light','light',[S('hit','glint','Light draws to mouth',{offsetY:-.15,scale:.5,scaleOut:.1,scaleOutDuration:2000}),S('aura','inward','Light consumed',{offsetY:-.15,scale:.7})],{delivery:'self'}),
 swampcall:E('Churning sodden terrain','earth',[A('area','glob','Sodden ground',{tintEnabled:true,colorize:true,tint:'#746d40'}),A('aura','cracks','Churning soil')],{nativeArea:true}),
 'swear-oath':E('Declared oath','ward',[S('hit','sound','Oath declared',{scale:.75}),S('aura','holy','Oath commitment')]),
 'sweet-dream':E('Enchanting dream','mind',[B('hit','sleep','Dream begins'),B('aura','stars','Enchanting dream imagery',{scale:.85,offsetY:-.25})]),
 'sweetest-solstice':E('Communal soup ceremony','healing',[S('hit','glob','Cauldron soup',{below:true,scale:.7}),S('aura','smoke','Cooking steam',{offsetY:-.25}),S('cast','heart','Communal goodwill',{scale:.55})]),
 'symphony-of-the-unfettered-heart':E('Liberating symphony','sonic',[S('cast','music','Symphony'),B('hit','sound','Liberating harmony'),B('aura','chain','Fetters counteracted',{scaleOut:.2,scaleOutDuration:2600})]),
 'synaptic-pulse':E('Pulsating mental blast','mind',[A('area','wave','Mental pulse'),A('aura','mind','Synaptic disruption',{scale:.7})],{nativeArea:true}),
 synesthesia:E('Rewired sensory input','mind',[B('hit','eyes','Visual input',{offsetY:-.3,scale:.55}),B('aura','music','Mixed sensory channels'),B('cast','stars','Color bursts',{subject:'targets',kind:'impact',scale:.75})]),
 'take-its-course':E('Affliction progression','poison',[B('hit','poison','Affliction selected',{scale:.65}),B('aura','clock','Affliction course',{scale:.7})]),
 'take-root':E('Roots reinforce grip','plant',[B('hit','roots','Roots sprout',{below:true}),B('aura','vine.complete','Roots secure stance',{below:true,scale:.85})],{symbolic:false}),
 'talking-corpse':E('Corpse memory speech','spirit',[B('hit','skull','Corpse memories',{scale:.5}),B('aura','sound','Corpse voice',{offsetY:-.2,scale:.7})]),
 tanglecurse:E('Fungal terrain curse','plant',[B('hit','roots','Fungal growth',{below:true,scale:1.7}),B('aura','fumes','Floating spores',{scale:1.5})]),
 'tattoo-whispers':E('Mouth tattoo invocation','sonic',[B('hit','rune','Shared tattoo design',{offsetX:.25,scale:.5}),B('aura','mute','Silent mouth motif',{offsetX:.25,scale:.45})]),
 'tear-the-veil':E('Universe Void tear','void',[A('area','vortex','Void waves draw inward'),A('hit','sphere_of_annihilation','Central tear',{scale:.083}),A('aura','dark','Void barrier weakens',{opacity:.45})],{nativeArea:true,castingOnly:false}),
 'telekinetic-haul':E('Object telekinesis','force',[B('hit','palm','Object held telekinetically'),B('aura','strands','Object suspension',{offsetY:-.2})]),
 'telekinetic-rend':E('Violent telekinetic axis','force',[A('area','strands','Telekinetic axis',{tween:[['rotation',-45,45,1800]]}),A('aura','cracked','Rending pressure')],{nativeArea:true,castingOnly:false}),
 'telepathic-bond':E('Planetary mental bond','mind',[T('link','Telepathic bond'),B('hit','mind','Linked minds',{offsetY:-.3,scale:.6})]),
 telepathy:E('Two-way mental speech','mind',[S('hit','mind','Mental communication',{offsetY:-.3,scale:.65}),S('aura','script','Shared mental language',{offsetY:-.5,scale:.45})]),
 'teleportation-circle':E('Destination circle invocation','teleport',[S('hit','rune','Destination inscription',{below:true}),S('aura','ward','Portal invocation',{below:true,scale:1.4})]),
 'tempest-touch':E('Clinging icy water','water',[B('hit','glob','Icy water clings'),B('aura','ice','Cold water mass',{scale:.85})],{castingOnly:false}),
 'temporal-distortion':E('Unpredictable time warp','time',[B('hit','clock','Temporal warp',{offsetY:-.3}),B('aura','shimmer','Mind and body distortion',{tween:[['scale.x',.7,1.2,1800]],opacity:.65})]),
 'temporal-twin':E('Recent past duplicate','time',[B('hit','clock','Recent past opens'),D('Temporal ally duplicate',{copies:1,copySpread:0,offsetX:1,opacity:.7}),B('aura','shimmer','Transient duplicate',{offsetX:1})]),
 'temporal-ward':E('Doorway time ward','time',[B('hit','ward','Doorway ward'),B('aura','clock','Temporal trap',{scale:.6})]),
 'temporary-glyph':E('Stored hostile glyph','ward',[A('area','ward','Temporary glyph'),A('aura','gem','Stored hostile spell',{scale:.55})],{delivery:'burst',previewArea:{type:'square',value:5},nativeArea:true}),
 'temporary-possession':E('Thrall spirit catalyst','void',[B('hit','skull','Thrall destruction'),B('aura','soul','Possession potential')]),
 'temporary-tool':E('Simple tool conjuration','transform',[S('hit','tool','Temporary tool',{offsetX:.35,scale:.65}),S('aura','shimmer','Conjured tool',{offsetX:.35,scale:.75})]),
 'tempt-fate':E('Polarized fortune','divination',[B('hit','die','Dire or uneventful fate',{scale:.65}),B('aura','clock','Decisive moment',{scale:.6})]),
 'terminate-bloodline':E('Bloodline curse invocation','void',[B('hit','poison','Wasting disease petition',{scale:.65}),B('aura','skull','Bloodline curse intent')]),
 'the-four-hunters':E('Four hunters tale','divination',[S('cast','sound','Hunters story'),B('hit','stars','Falling star motif',{offsetY:-.35}),B('aura','rune','Hunter attribute intent',{scale:.65})]),
 'the-unseeing-blade-master':E('Incense sword forms','metal',[S('hit','smoke','Incense cloud'),S('aura','sword','Sword forms'),P('spin','Training turn')]),
 'the-worlds-a-stage':E('Fate performance','sonic',[S('hit','music','Stage performance'),S('aura','script','Prepared dramatic script'),S('cast','die','Fate invocation',{scale:.5})]),
 'thermal-remedy':E('Restorative ingredients','healing',[B('hit','glob','Prepared food or drink',{scale:.65}),B('aura','heart','Restorative properties',{scale:.55})]),
 'thermal-stasis':E('Thermal equilibrium','ward',[B('hit','icon.snowflake.blue','Cold resistance',{offsetX:-.35,scale:.45}),B('aura','shield','Thermal protection'),B('cast','fire','Fire resistance',{subject:'targets',kind:'impact',offsetX:.35,scale:.45})]),
 'thicket-of-knives':E('Phantom weapon arms','illusion',[D('Phantom weapon arms',{copies:3,copySpread:.25,opacity:.4}),S('hit','shimmer','Arm illusions',{offsetX:.35,scale:.85})]),
 'thief-of-fortune':E('Benefit siphon','force',[T('link','Beneficial magic siphon',{travelOrigin:'target'}),S('hit','gem','Borrowed benefit',{scale:.65}),S('aura','strands','Shared magical energy')]),
 'thrall-charge':E('Thrall attack command','void',[P('dodge','Thrall charge gesture','targets'),B('hit','fists','Thrall Strike'),B('aura','skull','Thrall attack empowerment',{scale:.55})],{castingOnly:false}),
 'thunderous-strike':E('Weapon sonic wave','sonic',[S('cast','staff','Two-handed weapon swing'),F('sound','Sonic vibration cone'),B('hit','fists','Weapon contact')],{nativeArea:true,castingOnly:false}),
 'tidal-surge':E('Moving tidal wave','water',[B('hit','water','Wave carries target'),B('aura','glob','Tidal force',{below:true})]),
 'time-beacon':E('Turn rewind beacon','time',[S('hit','clock','Temporal beacon',{below:true}),S('aura','glint','Beacon point',{below:true,scale:.6})]),
 'time-jump':E('Paused-time travel','time',[S('hit','clock','Time pauses'),P('dodge','Temporal movement gesture'),D('Temporal afterimage',{copies:1,copySpread:.3,opacity:.3}),S('aura','shimmer','Time resumes')],{castingOnly:false}),
 'time-pocket':E('Item future pocket','time',[B('hit','clock','Item sent forward'),B('aura','shimmer','Item disappears',{scaleOut:.1,scaleOutDuration:2300})]),
 'time-skip':E('Ally time acceleration','time',[B('hit','clock','Moments advanced'),B('aura','winds','Next turn readiness',{below:true,scale:.75})]),
 'tomorrows-dawn':E('Golden dawn radiance','light',[S('hit','sun','New dawn light',{offsetY:-.35,scale:.7}),A('area','light','Dawn radiance'),S('aura','shield','Mental resilience',{opacity:.45})],{delivery:'emanation',previewArea:{type:'emanation',value:20},nativeArea:true}),
 'tortoise-and-the-hare':E('Speed transfer','time',[B('hit','clock','Foe time slows'),T('link','Speed siphoned',{travelOrigin:'target'}),S('aura','winds','Speed potential')]),
 'torturous-trauma':E('Internal organ pressure','force',[B('hit','heart','Internal organ pain',{scale:.45,maskToken:true}),B('aura','field','Internal pressure',{scale:.65,opacity:.5})],{castingOnly:false}),
 'touch-of-death':E('Death word preparation','void',[B('hit','fists','Unarmed contact'),B('aura','skull','Death word prepared',{scale:.5,offsetY:-.35})],{castingOnly:false}),
 'touch-of-the-moon':E('Forehead moon mark','light',[B('hit','moon','Forehead moon',{scale:.35,offsetY:-.4}),B('aura','glint','Soft moonlight',{scale:.85})]),
 'touch-of-the-void':E('Void infusion','void',[B('hit','dark','Void energy touch'),B('aura','strands','Void infusion',{opacity:.7})],{castingOnly:false}),
 'touch-of-undeath':E('Undeath touch','void',[B('hit','skull','Undeath influence',{scale:.6}),B('aura','inward','Life force attacked')],{castingOnly:false}),
 transmigrate:E('Kiln ritual preparation','spirit',[S('cast','smoke','Incense'),S('hit','glob','Clay beds',{below:true,tintEnabled:true,colorize:true,tint:'#bc9578'}),S('aura','feather','Upright heron feathers'),S('area','fire','Kiln fire',{scale:1.6,opacity:.5})]),
 'travel-by-turtle':E('Sea turtle invocation','water',[S('hit','water','Water journey'),S('aura','shield','Turtle shell intent',{below:true,scale:1.6})]),
 'traveling-workshop':E('Apparition tools','transform',[S('hit','tool','Ephemeral tools',{offsetX:.35,scale:.75}),S('aura','soul','Crafter apparition',{opacity:.45}),S('cast','script','Procedural guidance',{scale:.55,offsetY:-.4})]),
 'tree-of-seasons':E('Seasonal seedpod tree','plant',[S('hit','plants','Small tree sprouts'),S('aura','gem','Four seedpods',{repeats:4,repeatGap:300,scale:.45}),S('cast','leaf','Tree foliage')]),
 'tremor-signs':E('Ground vibration message','earth',[S('cast','wave','Tremor message',{below:true}),T('link','Ground vibration path',{below:true}),B('hit','sound','Received tremors',{below:true,scale:.75})]),
 'tricksters-mirrors':E('One distorted mirror','illusion',[D('Reflected image',{copies:1,copySpread:0,offsetX:.7,opacity:.5}),S('hit','bubble','First mirror',{offsetX:.7,scale:.7}),S('aura','shimmer','Distorted reflection',{offsetX:.7,scale:.75})]),
 'tricksters-twin':E('Phantasmal caster twin','illusion',[D('Caster twin',{subject:'source',copies:1,copySpread:0,offsetX:1,opacity:.65}),S('hit','shimmer','Twin appearance',{offsetX:1})]),
 'trim-the-blight':E('Shimmering blight purge','spirit',[F('shimmer','Shimmering cleansing energy',{fanCount:7}),S('cast','leaf','Blight trimming intent',{opacity:.55})],{nativeArea:true}),
 'true-target':E('Future attack visions','divination',[B('hit','eyes','Future defenses',{offsetY:-.35,scale:.55}),B('aura','die','Best possible attacks',{scale:.65}),B('cast','script','Shared future vision',{subject:'targets',kind:'impact',offsetY:-.5,scale:.5})]),
 truesight:E('True form perception','divination',[S('hit','eyes','True sight',{offsetY:-.3,scale:.55}),S('aura','insight','Illusions examined',{scale:.6,offsetY:-.5})]),
 truespeech:E('Universal spoken language','sonic',[B('hit','sound','Universal speech',{offsetY:-.2,scale:.75}),B('aura','script','Language comprehension',{scale:.6})]),
 'turbulent-tide':E('Weapon water surge','water',[S('cast','glob','Weapon water sheath',{offsetX:.35,scale:.7}),B('hit','fists','Improvised Strike'),S('aura','water','Sheath surges outward',{scale:1.6})],{castingOnly:false}),
 'umbral-extraction':E('Shadow spell pocket','shadow',[S('hit','dark','Ephemeral shadow pocket',{offsetX:.25,scale:.8}),S('aura','gem','Empty spell reserve',{scale:.6})]),
 'umbral-graft':E('Shadow benefit graft','shadow',[S('hit','shimmer','Shadow reflection'),S('aura','dark','Spell storage prepared'),S('cast','palm','Steal prepared',{offsetX:.25,scale:.55})]),
 'umbral-mindtheft':E('Shadow knowledge pocket','shadow',[S('hit','script','Lore storage prepared',{offsetY:-.35}),S('aura','dark','Shadow mind pocket',{offsetY:-.25,scale:.75})]),
 'unbearable-cacophony':E('Sound amplification invocation','sonic',[S('hit','sound','Sound amplification'),S('aura','note','Cacophony invocation',{scale:.7})]),
 'unblinking-flame-emblem':E('Fiery tracking sigil','fire',[B('hit','ward','Fiery sigil',{scale:.65}),B('aura','fire','Flame emblem',{scale:.75}),B('cast','eyes','Projected sight',{subject:'targets',kind:'impact',offsetY:-.3,scale:.45})]),
 'unblinking-flame-revelation':E('Revealing foe flame','fire',[B('hit','fire','Revealing flame'),B('aura','eyes','Illusions examined',{scale:.55,offsetY:-.3})]),
 'unbounded-sphere':E('Looping planar boundary','teleport',[A('area','bubble','Unbounded boundary'),A('aura','strands','Looping spatial threads',{opacity:.6})],{nativeArea:true}),
 'unbreaking-wave-advance':E('Mighty water wave','water',[A('area','waterCone','Buffeting wave')],{nativeArea:true,castingOnly:false,symbolic:false}),
 'unbreaking-wave-barrier':E('Repelling water barrier','water',[A('area','water_splash.circle.01.blue','Wave barrier'),S('hit','shield','Barrier defense',{scale:.7})],{nativeArea:true}),
 'unbreaking-wave-containment':E('Constricting water strands','water',[B('hit','strands','Constricting wave strands'),B('aura','glob','Water wraps target',{opacity:.75})]),
 'unbreaking-wave-vapor':E('Concealing vapor','water',[S('hit','fog','Concealing vapor'),S('aura','shield','Vapor defense',{opacity:.45})]),
 'uncouple-memory':E('Partitioned memory invocation','mind',[S('hit','mind','Primary mind',{offsetX:-.3,offsetY:-.3,scale:.55}),S('aura','script','Hidden memory petition',{offsetX:.3,offsetY:-.3,scale:.55})]),
 'undeaths-blessing':E('Grave touch blessing','void',[B('hit','skull','Touch of the grave',{scale:.6}),B('aura','heart','Undeath healing affinity',{scale:.5})]),
 'under-sunless-skies':E('Sunless sky','shadow',[A('area','dark','Sun darkens'),A('aura','eyes','Greater darkvision',{scale:.5,opacity:.5}),S('hit','shield','Allied resilience')],{delivery:'burst',previewArea:{type:'burst',value:5280},nativeArea:true}),
 'undermine-reality':E('Substance stealing shadow','shadow',[B('hit','void','Shadow tendrils'),B('aura','shimmer','Quasi-real substance',{maskToken:true,opacity:.5})]),
 undertaker:E('Epitaph and disturbed earth','void',[S('cast','sound','Whispered epitaph',{scale:.7}),B('hit','cracks','Earth disturbed',{below:true}),B('aura','skull','Grave promise',{scale:.55})],{castingOnly:false}),
 'unexpected-windfall':E('Heavy treasure rain','metal',[B('hit','gem','Heavy trinkets',{offsetY:-.5,tween:[['position.y',-.5,.4,2400]],scale:.65}),B('aura','rock','Stone treasures fall',{below:true})]),
 'unfettered-mark':E('Freedom tattoo invocation','ward',[B('hit','rune','Rare ink tattoo',{scale:.55,offsetX:.25}),B('aura','chain','Freedom intention',{scale:.75,scaleOut:.2,scaleOutDuration:2800})]),
 'unfettered-movement':E('Hindrance repulsion','ward',[B('hit','chain','Hindrance releases',{scaleOut:.2,scaleOutDuration:2600}),B('aura','shield','Movement protection',{opacity:.6})]),
 'unfettered-pack':E('Environmental freedom','plant',[B('hit','leaf','Vegetation hindrance fades',{below:true,scaleOut:.2,scaleOutDuration:2600}),B('aura','winds','Travel freedom',{below:true})]),
 'unfolding-wind-buffet':E('Air unarmed buffet','wind',[S('cast','winds','Air surrounds fists'),B('hit','fists','Three unarmed Strikes',{repeats:3,repeatGap:500}),B('aura','winds','Buffeting air')],{castingOnly:false}),
 'unfolding-wind-crash':E('Airborne landing crash','wind',[S('cast','winds','Jump air'),P('levitate','Jump lift'),A('hit','cracks','Landing force'),A('area','wave','Landing shockwave')],{delivery:'burst',previewArea:{type:'burst',value:20},nativeArea:true,castingOnly:false}),
 'unfolding-wind-rush':E('Rushing wind travel','wind',[S('hit','winds','Rushing wind'),P('dodge','Wind travel gesture'),S('aura','winds','Wind wake',{scale:1.5})],{castingOnly:false}),
 'unholy-army':E('Unholy legion invocation','void',[S('hit','void','Legions rise'),S('aura','skull','Unchosen squadron intent',{scale:.65})]),
 unity:E('United defense','ward',[T('link','United defensive bond'),B('hit','shield','Shared saving defense'),S('aura','holy','Caster defense')]),
 'unravel-existence':E('Reality tearing','force',[A('area','strands','Reality unravels',{scaleOut:.3,scaleOutDuration:3000}),A('aura','dust','Substance fragments',{opacity:.55})],{nativeArea:true,castingOnly:false}),
 'unrelenting-observation':E('Perfect tracking sensor','divination',[B('hit','eyes','Tracked subject',{offsetY:-.3,scale:.55}),B('aura','shimmer','Ghostly tracked image'),D('Observed silhouette',{copies:1,copySpread:0,opacity:.35})],{delivery:'target'}),
 'unsealing-of-secrets':E('Spirit writing petition','spirit',[B('hit','script','Blank parchment'),B('aura','soul','Writing spirit invoked',{opacity:.5})]),
 'unseen-heralds':E('Illusory mouth invocation','sonic',[S('hit','mute','Illusory mouths prepared',{scale:.7}),S('aura','sound','Voice transmission intent')]),
 'unsettling-knowledge':E('Hidden knowledge shared','mind',[B('hit','script','Unsettling knowledge',{offsetY:-.3,scale:.65}),B('aura','horror','Upsetting insight',{offsetY:-.3,scale:.7})]),
 'utter-destruction':E('Destructive screech','sonic',[F('sound','Destructive voice cone',{fanCount:5}),S('cast','skull','Void-laced voice',{scale:.55})],{nativeArea:true,castingOnly:false}),
 'vampiric-exsanguination':E('Blood and life withdrawal','blood',[A('area','detect_magic.cone','Life withdrawal area',{opacity:.15}),B('hit','blood','Blood draws from victims',{subject:'targets'}),T('link','Life draws to caster',{travelOrigin:'target'}),S('aura','inward','Life gathers')],{nativeArea:true,castingOnly:false}),
 'vampiric-revelry':E('Blood life siphon','blood',[A('area','blood','Blood and life essence'),S('hit','inward','Life energy gathers'),S('aura','heart','Life reserve',{scale:.6})],{delivery:'emanation',previewArea:{type:'emanation',value:20},nativeArea:true,castingOnly:false}),
 'vanishing-tracks':E('Obscured tracks','illusion',[B('hit','footprints','Tracks fade',{below:true,scaleOut:.2,scaleOutDuration:2600}),B('aura','dust','Track concealment',{below:true,opacity:.6})]),
 'veil-of-broken-reality':E('Imperceptible passing time','time',[A('area','shimmer','Reality veil'),A('aura','clock','Hidden time passage',{opacity:.45})],{delivery:'burst',previewArea:{type:'burst',value:528000},nativeArea:true}),
 'veil-of-confidence':E('Confidence veil','mind',[S('hit','fear','Fear ebbs',{scale:.55,scaleOut:.2,scaleOutDuration:2500}),S('aura','shield','Confident defense')]),
 'veil-of-spirits':E('Spiritual mist veil','spirit',[A('area','fog','Misty veil'),A('aura','soul','Spiritual essence',{opacity:.5})],{nativeArea:true}),
 'vengeful-glare':E('Wrathful gaze','mind',[S('cast','eyes','Vengeful gaze',{scale:.45,offsetY:-.25}),B('hit','fear','Wrath reaches foe',{scale:.6})]),
 ventriloquism:E('Displaced vocal sound','sonic',[S('hit','sound','Projected vocalization',{scale:.7,offsetX:.8}),S('aura','note','Apparent voice origin',{scale:.45,offsetX:.8})]),
 'verdant-sprout':E('Energized seed','plant',[S('hit','gem','Seed imbued',{scale:.35,offsetX:.25}),S('aura','leaf','Primal seed energy',{scale:.7})]),
 'vindicators-judgment':E('Quarry judgment','ward',[S('cast','sound','Judgment pronounced'),B('hit','holy','Judged quarry',{scale:.65}),B('aura','cracked','Future attack weakness',{scale:.5})]),
 'vision-of-beauty':E('Phantasmal beauty invocation','illusion',[S('hit','shimmer','Vague illusion outline',{offsetX:.8,opacity:.55}),S('aura','heart','Beauty intent',{offsetX:.8,scale:.5})]),
 'vital-luminance':E('Vitality beacon reservoir','vitality',[A('area','light','Beacon radiance'),S('hit','inward','Luminance gathers'),S('aura','gem','Luminance reservoir',{scale:.6})],{delivery:'emanation',previewArea:{type:'emanation',value:30},nativeArea:true}),
 'vital-singularity':E('Shared life invocation','healing',[T('link','Life sharing petition'),S('hit','heart','Primary life essence'),B('aura','heart','Companion life essence',{scale:.65})]),
 'vitality-lash':E('Creation energy lash','vitality',[T('link','Vitality lash'),B('hit','light','Corrupted essence scoured',{scale:.9})],{castingOnly:false}),
 'vitrifying-blast':E('Glass shard cone','metal',[F('ice','Glass shards',{fanCount:7})],{nativeArea:true,castingOnly:false}),
 'voice-on-the-breeze':E('Wind-carried message','wind',[S('cast','sound','Whisper to wind',{scale:.65}),A('area','winds','Message breeze'),A('aura','script','Whispered message',{scale:.6})],{nativeArea:true}),
 'void-harvest':E('Void conduit invocation','void',[S('hit','dark','Sky darkens'),S('aura','vortex','Void conduit intent',{opacity:.55})]),
 'voracious-gestalt':E('Voracious spirit entity','void',[A('area','soul','Spirit entity'),A('aura','vortex','Devouring essence'),A('hit','skull','Voracious spirit',{scale:.5})],{nativeArea:true,castingOnly:false}),
 'wails-of-the-damned':E('Damned souls lament','void',[S('cast','sound','Lament howl'),A('area','skull','Damned souls'),A('aura','wave','Lament carries')],{nativeArea:true,castingOnly:false}),
 'waking-dream':E('Vivid waking dreams','mind',[B('hit','sleep','Dreamlike imagery'),B('aura','horror','Imagined threats',{offsetY:-.35,scale:.6})]),
 'wall-of-fire':E('Blazing fire wall','fire',[A('area','fireWall','Vertical flame wall')],{delivery:'line',pattern:'lineBarrier',previewArea:{type:'line',value:60,width:5},symbolic:false}),
 'wall-of-flesh':E('Living flesh wall','blood',[A('area','blood','Living flesh segments'),A('aura','heart','Living tissue',{scale:.5})],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:30,width:3}}),
 'wall-of-force':E('Invisible force wall','force',[A('area','forceWall','Invisible force barrier',{opacity:.45})],{delivery:'line',pattern:'lineBarrier',previewArea:{type:'line',value:50,width:1},symbolic:false}),
 'wall-of-ice':E('Opaque ice wall','cold',[A('area','iceLine','Ice barrier')],{delivery:'line',previewArea:{type:'line',value:60,width:1}}),
 'wall-of-mirrors':E('Reflective glass wall','illusion',[A('area','shimmer','Reflective glass segments'),A('aura','bubble','Solid glass',{scale:.8,opacity:.5})],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:50,width:1}}),
 'wall-of-radiance':E('Brilliant light wall','light',[A('area','glint','Brilliant light segments')],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:1}}),
 'wall-of-shadow':E('Pure darkness wall','shadow',[A('area','dark','Darkness sheet')],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:1}}),
 'wall-of-shrubs':E('Regional shrub line','plant',[A('area','plants','Bushes rise'),A('aura','leaf','Shrub foliage')],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:1}}),
 'wall-of-stone':E('Solid stone wall','earth',[A('area','rock','Stone segments'),A('aura','cracks','Stone joins',{opacity:.5})],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:120,width:1}}),
 'wall-of-thorns':E('Thorny bramble wall','plant',[A('area','roots','Thorn brambles'),A('aura','leaf','Bramble foliage',{opacity:.6})],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:5}}),
 'wall-of-virtue':E('Celestial light wall','spirit',[A('area','glint','Celestial light segments'),A('aura','holy','Celestial virtue',{scale:.6})],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:5}}),
 'wall-of-water':E('Upright water wall','water',[A('area','glob','Water wall segments'),A('aura','water','Water surface')],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:60,width:5}}),
 'wall-of-wind':E('Gusting wind wall','wind',[A('area','windWall','Vertical gust barrier')],{delivery:'line',pattern:'lineBarrier',previewArea:{type:'line',value:60,width:5},symbolic:false}),
 'ward-domain':E('Sanctum ward preparation','ward',[S('cast','smoke','Burning incense'),S('hit','water','Doorframe anointing'),S('aura','rune','Silver entry lines',{below:true})]),
 'warp-mind':E('Scrambled mental faculties','mind',[B('hit','mind','Mental faculties scramble',{offsetY:-.3}),B('aura','dizzy_stars','Conflicting sensory input',{offsetY:-.5,scale:.65})]),
 'warriors-regret':E('Violence regret curse','mind',[B('hit','heart','Regret planted',{scale:.55}),B('aura','skull','Violence consequence intent',{offsetY:-.3,scale:.5})]),
 'wash-your-luck':E('Personal luck adjustment','divination',[S('hit','die','Luck cleansed',{scale:.6}),S('aura','glint','Personal lucky gesture',{scale:.7}),P('pulse','Garment adjustment')]),
 'water-breathing':E('Underwater breathing','water',[B('hit','bubble','Underwater breath',{offsetY:-.2,scale:.65}),B('aura','glob','Water breathing affinity',{scale:.85})]),
 'water-walk':E('Liquid surface footing','water',[B('hit','water','Water surface footing',{below:true,offsetY:.3,scale:.8}),B('aura','shield','Surface support',{below:true,offsetY:.3,scale:.75})]),
 waterproof:E('Hydrophobic surface','water',[B('hit','bubble','Hydrophobic coating',{maskToken:true}),B('aura','water','Water repelled',{scaleOut:1.4,scaleOutDuration:2500})]),
 'waters-of-prediction':E('Still water divination','divination',[B('hit','glob','Still natural pool',{below:true}),B('aura','eyes','Collective future petition',{below:true,scale:.55})]),
 'wave-of-despair':E('Despair wave','mind',[F('fear','Despair symbols',{fanCount:5}),S('cast','heart','Despair invocation',{scale:.5})],{nativeArea:true}),
 'weapon-of-judgment':E('Hovering judgment weapon','spirit',[B('hit','sword','Judgment weapon',{offsetY:-.8,scale:1.2}),B('aura','holy','War or peace decree',{offsetY:-.4,scale:.55})]),
 web:E('Sticky web terrain','web',[A('area','web','Sticky web'),A('aura','web','Web strands',{opacity:.5})],{nativeArea:true,symbolic:false}),
 'web-of-eyes':E('Shared vision sensors','divination',[B('hit','eyes','Sensor above eyes',{scale:.4,offsetY:-.45}),B('aura','strands','Vision sharing link',{scale:.75})]),
 'whispers-of-a-dead-goddess':E('Goddess whispers','sonic',[A('area','sound','Mysterious whispers'),A('aura','skull','Dead goddess voice',{scale:.5,opacity:.5})],{nativeArea:true}),
 'whispers-of-the-void':E('Baleful words made physical','void',[S('cast','sound','Baleful whisper'),A('area','script','Physical secret words'),A('aura','skull','Life weakening words',{scale:.55})],{nativeArea:true}),
 'wild-allegiance':E('Peaceful beast communion','plant',[S('hit','palm','Beasts approached'),S('aura','heart','Wild friendship petition',{scale:.65})]),
 'wild-feast':E('Flora fauna hostility invocation','plant',[S('hit','leaf','Local flora'),S('aura','claw','Latent hostility petition')]),
 'wild-winds-stance':E('Flowing winds stance','wind',[S('hit','winds','Flowing winds'),S('aura','shield','Ranged defense',{opacity:.5}),P('pulse','Wind stance')]),
 'wind-whispers':E('Rumor woven into breezes','wind',[S('hit','winds','Numerous breezes'),S('aura','script','Rumor woven',{offsetY:-.25,scale:.65})]),
 'winning-streak':E('Energizing fortune','divination',[B('hit','die','Good fortune',{scale:.6}),B('aura','winds','Energized readiness',{below:true})]),
 'winters-breath':E('Tea ceremony','water',[S('hit','glob','Freshly brewed tea',{scale:.6}),S('aura','smoke','Tea steam',{offsetY:-.2}),S('cast','leaf','Tea ingredients',{scale:.65})]),
 'wisdom-of-the-winds':E('Air spirit guidance','wind',[S('hit','winds','Air spirits asked'),S('aura','script','Guidance intent',{offsetY:-.3,scale:.65})]),
 wish:E('Declared desire invocation','force',[B('hit','sound','Wish declared'),B('aura','strands','Reality fabric petition')]),
 'wish-market':E('Ghostly merchant contracts','spirit',[S('hit','soul','Ghostly merchants'),S('aura','script','Offered contracts',{scale:.75}),S('cast','palm','Offer accepted',{scale:.65})]),
 'wish-twisted-form':E('Defenses unravel','mind',[B('hit','cracked','Defenses weakened',{scale:.65}),B('aura','strands','Strengths twisted',{scaleOut:.4,scaleOutDuration:2500})]),
 'withering-grasp':E('Substance erosion touch','void',[B('hit','palm','Withering touch',{scale:.7}),B('aura','dust','Organic decay',{maskToken:true,saturation:-1})],{castingOnly:false}),
 'wood-walk':E('Wooden climbing support','plant',[S('hit','roots','Wood shapes for travel'),P('levitate','Branch lift gesture'),S('aura','leaf','Branches guide movement')],{castingOnly:false}),
 'wooden-double':E('Wooden substitute','plant',[D('Wooden substitute',{subject:'source',copies:1,copySpread:0,opacity:.8}),S('hit','leaf','Wooden block',{scale:1.2}),P('dodge','Evasive Step'),S('aura','dust','Wooden splinters')],{castingOnly:false}),
 'word-of-revision':E('Reality revision word','time',[S('cast','sound','Revision word'),B('hit','script','Story revised'),B('aura','clock','Fate revised',{scale:.65})]),
 'word-of-truth':E('Glowing deity symbol','ward',[S('hit','holy','Deity symbol',{offsetY:-.65,scale:.65}),S('aura','sound','True statement',{scale:.75})]),
 wordsmith:E('Written translation','mind',[B('hit','script','Text language shifts',{scale:.8}),B('aura','glint','Translated lettering',{scale:.65})]),
 'world-in-shadow':E('Night darkness invocation','shadow',[S('hit','moon','Night ritual',{offsetY:-.4,scale:.6}),S('aura','dark','Everlasting darkness intent')]),
 'youre-mine':E('Emotional control','mind',[B('hit','heart','Emotions manipulated',{scale:.65}),B('aura','strands','Control suggestion',{scale:.8})]),
 'zeal-for-battle':E('Shared righteous anger','mind',[T('link','Shared battle zeal'),B('hit','heart','Righteous anger',{scale:.65}),S('aura','die','Initiative fortune',{scale:.6})]),
 'zealous-conviction':E('Unshakable conviction','mind',[B('hit','holy','Conviction instilled'),B('aura','shield','Mental conviction defense'),B('cast','heart','Temporary vigor',{subject:'targets',kind:'impact',scale:.5})]),
 'zenith-star':E('Tracking star','light',[B('hit','stars','Sparkling star halo',{scale:.9}),B('aura','glint','Star rises',{offsetY:-.5,scale:.4,tween:[['position.y',-.5,-2,2600]]})]),
 'zombie-horde':E('Temporary zombie mass','void',[B('hit','skull','Thrall catalyst',{scale:.55}),A('area','palm','Zombie grasping mass'),A('aura','skull','Zombie horde',{scale:.65,opacity:.55})],{nativeArea:true}),
};

// Explicit definitions use slot geometry, not identity hashes or arbitrary hue.
export const GAP_C_MOTIFS=Object.fromEntries(Object.entries(REVIEWED).map(([slug,row])=>{
 const roots={cast:'',hit:'',aura:'',area:'',bolt:''};
 for(const node of row.nodes)if(node.asset){
  if(roots[node.slot]&&roots[node.slot]!==node.asset)throw Error(`Mixed artwork in ${slug}/${node.slot}`);
  roots[node.slot]=node.asset;
 }
 const hasFan=row.nodes.some(n=>n.type==='fan');
 const firstLocal=row.nodes.find(n=>n.asset&&n.type==='body')?.asset??'glint';
 for(const slot of ['cast','hit','aura'])roots[slot] ||= firstLocal;
 roots.bolt ||= ART.link;
 roots.area ||= hasFan?'detect_magic.cone':firstLocal;
 return [`gapC-${slug}`,{label:row.label,pattern:row.pattern??(hasFan?'coneObjectFan':row.areaLayout==='tiles'?'lineTiles':`gapC-${slug}`),...roots,
  symbolic:row.symbolic,castingOnly:row.castingOnly,
  ...(row.nativeArea?{nativeArea:true}:{}),theme:row.theme,
  ...(row.delivery?{delivery:row.delivery}:{}),...(row.previewArea?{previewArea:row.previewArea}:{}),
  ...(row.areaLayout?{areaLayout:row.areaLayout}:{})}];
}));
export const GAP_C_DESIGNS=Object.fromEntries(Object.keys(REVIEWED).map(slug=>[slug,[`gapC-${slug}`,'']]));

export function gapCLayers(spell,{fx,copy,pose,track,subject}){
 const slug=spell.design?.motif?.replace(/^gapC-/,'');
 const row=REVIEWED[slug];
 if(!row)return null;
 return row.nodes.map((node,index)=>{
  const extra={...node.options};
  const delay=extra.delay??index*450;
  delete extra.delay;
  const duration=Math.max(4500,(spell.design.mediaTiming?.[node.slot]?.duration??0)/(extra.playbackRate??1));
  if(extra.tween){extra.tracks=extra.tween.map(([property,from,to,span])=>track(property,from,to,span));delete extra.tween;}
  if(node.type==='copy')return copy(node.label,delay,4500,{...extra});
  if(node.type==='pose')return pose(node.motion,node.label,delay,1600,node.subject,.25,.35);
  if(node.type==='travel')return fx('travel','bolt',node.label,delay,duration,{scale:.6,fadeIn:150,fadeOut:450,...extra});
  if(node.type==='fan')return fx('projectile','bolt',node.label,delay,duration,{travelDestination:'area',areaLayout:'fan',fanCount:5,scale:.45,fadeIn:0,fadeOut:400,...extra});
  if(node.type==='area')return fx('template',node.slot,node.label,delay,duration,{scale:1,below:true,opacity:.9,fadeIn:400,fadeOut:700,areaLayout:row.areaLayout??'fit',...extra});
  const who=extra.subject??subject;
  const kind=who==='targets'?'impact':'cast';
  return fx(kind,node.slot,node.label,delay,duration,{kind,subject:who,scale:1,fadeIn:300,fadeOut:650,...extra});
 });
}
