// Explicit recipes for the pinned missing-spell slice 300..599.
// Recipes illustrate invocation and immediate described fiction. Outcome,
// movement destinations, creature choices and subsequent turns remain rules.
const body = (root, label, extra = {}) => ({kind:'body',root,label,...extra});
const self = (root, label, extra = {}) => body(root,label,{subject:'source',...extra});
const field = (root, label, extra = {}) => ({kind:'field',root,label,...extra});
const link = (root, label, extra = {}) => ({kind:'link',root,label,...extra});
const object = (root, label, extra = {}) => ({kind:'object',root,label,...extra});
const fan = (root, label, extra = {}) => ({kind:'fan',root,label,...extra});
const image = (label, extra = {}) => ({kind:'image',label,...extra});
const eye='eyes.01.dark_green.single', eyes='eyes.01.dark_green.many';
const rune='icon.runes.orange', text='icon.runes02.orange', signs='icon.runes03.orange';
const strands='energy_strands.complete.blue.01', tether='energy_strands.range.standard.purple.01';
const leaves='swirling_leaves.complete.01.green', petals='swirling_leaves.outburst.01.pink';
const plants='plant_growth.03.round.2x2.complete.greenyellow', vines='vine.complete.nature.group.01.green';
const frost='aura_themed.01.inward.complete.cold.01.blue', snow='icon.snowflake.blue';
const shield='icon.shield.green', heart='icon.heart.pink', skull='icon.skull.purple';
const sound='soundwave.02.blue', notes='music_notations.treble_clef.blue';
const mist='smoke.puff.centered.grey', fog='fog_cloud.01.white';
const shimmer='shimmer.01.blue', glint='glint.yellow.few';
const water='liquid.blob.blue', splash='water_splash.circle.01.blue';
const particles='particles.outward.greenyellow.01.01', inward='particles.inward.greenyellow.01.01';
const voidField='energy_field.02.above.blue', gravity='template_circle.vortex.loop.blue';
const portal='portals.vertical.ring', ward='ward.rune.yellow.01';
const fear='icon.fear.dark_purple', horror='icon.horror.purple', stun='icon.stun.purple';
const fire='flames.01.orange', poison='icon.poison.dark_green';
const dice='icosahedron.roll.blue', stars='twinkling_stars.points07.white';
const pulse='extras.tmfx.radar.circle.pulse.01.normal';
const profiles=[];
const add=(slug,label,nodes,extra={})=>profiles.push({slug,label,nodes,symbolic:true,castingOnly:true,...extra});

add('fishing-spot','Fishing pool',[self(water,'Extraplanar pool',{below:true,scale:1.6}),self(splash,'Pool ripples',{below:true,delay:400}),self(glint,'Fishing rod glints',{scale:.5,offsetX:.5,offsetY:-.3})]);
add('flame-dancer','Burning hands and feet',[body(fire,'Hands aflame',{offsetX:.4,scale:.5}),body(fire,'Feet aflame',{offsetY:.5,scale:.6}),body(fire,'Hair aflame',{offsetY:-.45,scale:.45})]);
add('flame-wisp','Three fire wisps',[-.55,0,.55].map(x=>self('dancing_light.yellow','Fire wisp',{offsetX:x,offsetY:-.6,scale:.25})));
add('flames-of-ego','Beautiful flames',[body(fire,'Coruscating flames',{maskToken:true}),body(glint,'Flame beauty',{scale:.8,delay:500})]);
add('flaming-fusillade','Miniature suns',[self('flaming_sphere.200px.orange.01','Solar flames',{scale:.6,offsetX:-.7}),self('flaming_sphere.200px.orange.01','Solar flames',{scale:.6,offsetX:.7,delay:250}),self(fire,'Flame barrage gathers',{offsetY:-.65,scale:.5,delay:500})]);
add('flammable-fumes','Volatile gases',[field('fumes.04.complete.grey','Invisible gas boundary',{opacity:.18}),field(poison,'Toxic gas symbol',{scale:.25,delay:500})],{nativeArea:true});
add('flashy-disappearance','Colorful smoke departure',[self(mist,'Colorful smoke',{color:'#ce78ff',scale:1.3}),image('Vanishing silhouette',{subject:'source',opacity:.45,alphaOut:true})]);
add('flesh-tsunami','Wave of flesh',[body('liquid.splash02.red','Thrall flesh liquefies',{subject:'targets',scale:1.2}),fan('liquid.splash02.red','Sticky flesh wave',{fanCount:7})],{pattern:'coneObjectFan',delivery:'cone',previewArea:{type:'cone',value:60},castingOnly:false});
add('flowing-strike','Flowing water stride',[self(splash,'Water rushes behind',{offsetX:-.45,scale:1.3}),self('wind_stream.white','River current',{scale:1.2,rotation:90})]);
add('focusing-hum','Sustained hum',[self(sound,'Focused hum',{offsetY:-.15,scale:.7}),field(sound,'Hum fills the air',{opacity:.55})],{nativeArea:true});
add('fold-metal','Metal folds into a ball',[body('aura_themed.01.inward.complete.metal.01.grey','Metal folds',{scaleOut:.2,scaleOutDuration:1800}),body('icosahedron.simple.blue','Folded metallic ball',{scale:.3,delay:700})]);
add('font-of-serenity','Serenity beacon',[field('dancing_light.blueteal','Divine beacon',{scale:.3,below:false}),field('template_circle.aura.01.complete.small.bluepurple','Serene light',{opacity:.55,delay:300})],{nativeArea:true});
add('footholds-and-foothills','Terrain invocation',[self('ground_cracks.01.orange','Terrain lines',{below:true,scale:1.4,opacity:.5}),self(rune,'Terrain choice',{scale:.65,delay:550})]);
add('foraging-friends','Foraging call',[self(sound,'Cheerful whistle',{offsetY:-.25,scale:.55}),self(leaves,'Foraging invitation',{scale:1.2,delay:450}),self('footprints.monster.grey,footprints.shoe.grey','Small animal tracks',{below:true,scale:.6,delay:800})]);
add('force-fang','Force spike',[self('melee_attack.01.trail.01.blueyellow','Force fang',{scale:.8}),body('energy_attack.01.blue','Force contact',{scale:.75,delay:300})],{castingOnly:false});
add('foresee-the-path','Future movement insight',[self(eye,'Future movement',{offsetY:-.35,scale:.6}),link(tether,'Ally foresight',{opacity:.55,delay:400}),body(pulse,'Reaction prepared',{scale:.7,delay:700})]);
add('forge','Superheated metal',[body('aura_themed.01.inward.complete.metal.01.grey','Metal heats',{maskToken:true}),body(fire,'Superheating',{maskToken:true,delay:300})],{castingOnly:false});
add('forgotten-lines','Recovered writing',[body(text,'Missing lines return',{scale:.8}),body(eye,'Recovered information',{scale:.4,offsetY:-.4,delay:500})]);
add('form-of-the-sandpoint-devil','Sandpoint Devil invocation',[self('campfire.01','Ritual fire',{below:true,scale:.8}),self('ground_cracks.01.orange','Burial trench',{below:true,delay:600}),self('bats.complete.01.red','Wing offering',{scale:.5,delay:1000})]);
add('fortifying-brew','Restorative brew invocation',[self(water,'Restorative brew',{scale:.5,offsetY:.35}),self('fumes.steam','Brewing steam',{scale:.65,offsetY:-.35,delay:450}),self(heart,'Restoration petition',{scale:.45,delay:900})]);
add('fractious-echo','Spiritual echo',[self('unarmed_strike.physical.01.blue','Blow gathers',{scale:.75}),body(strands,'Spirit exposed',{delay:450}),image('Spiritual echo',{copies:1,offsetX:-.5,opacity:.3,saturation:-1,delay:650})],{castingOnly:false});
add('freedom','Freedom invocation',[body('markers.chain.spectral_standard.complete.02.blue','Magical bonds',{scale:1.2,opacity:.5}),body(ward,'Release petition',{scale:.7,delay:650})]);
add('freeze-time','Time stops',[self('icosahedron.simple.blue','Still moment',{scale:.8,playbackRate:.35}),image('Held instant',{subject:'source',copySpread:0,copies:1,opacity:.25,delay:500})]);
add('freezing-touch','Freezing touch',[body(frost,'Cold concentrates',{scale:.85}),body(snow,'Freezing point',{scale:.5,delay:500}),body('ice_spikes.radial.burst.white','Touch frost crystallizes',{scale:.75,delay:850})],{castingOnly:false});
add('frog-tongue','Extended tongue',[link(tether,'Tongue extends',{tint:'#c9799d',scale:.3}),body('liquid.splash02.red','Tongue tip',{scale:.4,delay:450})],{pattern:'tetherConnection',castingOnly:false});
add('frost-pillar','Ice pillar',[body('ice_spikes.radial.burst.white','Ice crystallizes',{scale:1.25}),body('shield_themed.above.ice.01.blue','Icy enclosure',{scale:1.3,delay:600})]);
add('frosts-touch','Object cooling',[body(frost,'Heat leaves the object',{scale:.7}),body(snow,'Cold object',{scale:.4,offsetY:-.25,delay:500})]);
add('frozen-lungs','Cold within lungs',[body(water,'Water pools within',{maskToken:true,scale:.6}),body(frost,'Lungs chill',{maskToken:true,scale:.8,delay:350})],{castingOnly:false});
add('fulminating-impact','Electromagnetic palm',[self('static_electricity.02.blue','Charged palm',{scale:.65,offsetX:.35}),self(sound,'Compressed vibration',{scale:.65,offsetX:.35,delay:250}),self('unarmed_strike.magical.01.blue','Charged blow',{scale:.85,delay:500})],{castingOnly:false});
add('fungal-exhalation','Mold spores',[self(mist,'Exhaled spores',{offsetY:-.1,scale:.5}),fan('particles.002.001.complete.few.blue','Toxic spores',{fanCount:7,tint:'#739863'})],{pattern:'coneObjectFan',nativeArea:true,castingOnly:false});
add('garden-of-death','Poisonous garden invocation',[self('liquid.splash02.red','Blood offering',{below:true,scale:.6}),self(splash,'Poisoned watering',{below:true,delay:350}),self(plants,'Garden petition',{below:true,delay:700})]);
add('garden-of-the-green-mans-growth','Green man invocation',[self(plants,'Verdant arrival invitation',{below:true,scale:1.2}),self(vines,'Green man branches',{scale:1.2,delay:700})]);
add('gathering-call','Sanctuary bond invocation',[self(ward,'Sanctuary seal',{below:true}),link(tether,'Return bond',{opacity:.55,delay:500}),body(signs,'Participant attunement',{scale:.5,delay:800})]);
add('geas','Binding rule invocation',[body(text,'Rule inscribed',{scale:.7}),body('markers.chain.spectral_standard.complete.02.blue','Oath connection',{opacity:.5,delay:650})]);
add('gentle-breeze','Soothing breeze',[field('wind_lines.01.01.white','Cool breeze',{opacity:.5}),field(leaves,'Restful air',{opacity:.55,delay:350})],{nativeArea:true});
add('gentle-landing','Arrested fall',[body('wind_lines.01.01.white','Magical updraft',{rotation:270,scale:1.1}),body('swirling_feathers.outburst.01.textured','Gentle descent',{scale:.6,delay:400})]);
add('ghostly-shift','Insubstantial body',[self(shimmer,'Partial phasing',{maskToken:true,opacity:.5}),image('Ghostly silhouette',{subject:'source',copySpread:0,opacity:.25,saturation:-1,delay:450})]);
add('ghostly-tragedy','Spiritual reenactment',[field('spirit_guardians.blueyellow.ring','Local spirits gather',{opacity:.45}),self(eye,'Past event scrutiny',{offsetY:-.4,scale:.5,delay:650})]);
add('ghostly-transcription','Glowing speech',[body(text,'Speech letters',{offsetY:-.5,scale:.7}),body(notes,'Spoken language',{offsetY:-.7,scale:.35,delay:600})]);
add('ghoulish-cravings','Raw meat craving',[body('bite.200px.red','Hunger image',{offsetY:-.25,scale:.6}),body(skull,'Ghoulish craving',{scale:.45,delay:500})]);
add('glacial-heart','Inner glacial cold',[body(water,'Inner moisture',{maskToken:true,scale:.55}),body(frost,'Bone-deep cold',{maskToken:true,delay:300}),body(snow,'Cold at the heart',{offsetY:.05,scale:.45,delay:650})],{castingOnly:false});
add('glamorize','Minor appearance detail',[self(shimmer,'Cosmetic finish',{maskToken:true}),self(glint,'Flattering detail',{offsetY:-.4,scale:.5,delay:550})]);
add('glance-of-the-divine','Divine supplication',[self(eye,'Divine attention petition',{offsetY:-.6,scale:.6}),self('ward.star.yellow.01','Offering and supplication',{scale:.8,delay:700})]);
add('glass-form','Transparent glass body',[body(shimmer,'Transparent glass',{maskToken:true,opacity:.45}),image('Glass silhouette',{copySpread:0,opacity:.3,saturation:-.8,delay:400})]);
add('glass-sand','Jagged glass fan',[self(particles,'Handful of sand',{scale:.45,offsetX:.4}),fan('icosahedron.simple.blue','Glass shards',{fanCount:7,scale:.28,delay:350})],{pattern:'coneObjectFan',nativeArea:true,castingOnly:false});
add('gleaming-pet','Otherworldly glow',[body('dancing_light.blueyellow','Intense companion light',{scale:1.25}),body(glint,'Glowing outline',{maskToken:true,delay:450})]);
add('glimmer-of-charm','Glittering charm aura',[self(glint,'Glittering presence',{maskToken:true}),field('swirling_sparkles.01.blue','Smooth charm aura',{opacity:.65,delay:250})],{nativeArea:true});
add('glimpse-the-truth','Unveiled sight',[self(eye,'Divine insight',{offsetY:-.35,scale:.55}),field(pulse,'Illusions surveyed',{opacity:.25,delay:300})],{nativeArea:true});
add('glossolalia','Scrambled language',[body(text,'Language scrambles',{offsetY:-.4,scale:.75}),body('icon.mute.dark_red','Unintelligible tongues',{offsetY:-.15,scale:.45,delay:550})]);
add('gnaw-at-the-moon','Moon offerings invocation',[self('celestial_bodies.planet.no_atmo.03.grey','Moon honored',{offsetY:-1,scale:.55}),self(water,'Tea offering',{offsetY:.4,scale:.4,delay:500}),self('bite.200px.red','Mooncake offering',{below:true,scale:.35,delay:850})]);
add('grasp-of-the-deep','Deep sea pressure',[body(water,'Phantasmal deep water',{opacity:.4}),body(voidField,'Pressure closes',{scaleIn:1.5,scaleInDuration:1500,scale:.8,delay:300})],{castingOnly:false});
add('grasping-grave','Skeletal arms',[field('melee_attack.02.bone.01','Skeletal arms',{opacity:.8}),field('black_tentacles.dark_purple','Grasping grave limbs',{delay:350,tint:'#dadbdc'})],{nativeArea:true,castingOnly:false});
add('grasping-vine','Ground vine',[self(vines,'Vine erupts',{below:true,scale:.75}),link(tether,'Vine connection',{delay:300,scale:.5,tint:'#5c884d'}),body(vines,'Curling vine',{delay:650})],{pattern:'tetherConnection'});
add('gravity-wave','Gravitic ripple',[self(voidField,'Gravity gathers',{scale:.7}),fan(sound,'Gravitic wave',{fanCount:7,tint:'#8b77aa',delay:300})],{pattern:'coneObjectFan',nativeArea:true,castingOnly:false});
add('gravity-well','Altered gravity sphere',[field(gravity,'Gravity well',{opacity:.65}),field(inward,'Gravity draws inward',{delay:400})],{nativeArea:true});
add('gray-shadow','Dying shadow summon',[body('drop_shadow','Shadow drawn forth',{below:true}),image('Adjacent shadow',{copies:1,offsetX:.85,tint:'#28232d',saturation:-1,opacity:.45,delay:450})]);
add('gritty-wheeze','Sand exhalation',[self(particles,'Grit exhaled',{offsetY:-.1,scale:.45}),fan(particles,'Sand cloud',{fanCount:7,tint:'#c7a77e',delay:300})],{pattern:'coneObjectFan',nativeArea:true,castingOnly:false});
add('guardians-aegis','Guardian bond invocation',[link(tether,'Guardian and ward',{opacity:.5}),body(shield,'Guardianship petition',{scale:.6,delay:500}),self(heart,'Shared burden',{scale:.5,delay:750})]);
add('hags-fruit','Fruit curse',[body(plants,'Fruit locus',{scale:.55}),body('sleep.symbol.pink','Slumber sealed',{scale:.4,delay:600})]);
add('halcyon-infusion','Innate magic infusion',[link(tether,'Magic imparted',{scale:.5}),body(text,'Spell knowledge opens',{offsetY:-.3,scale:.7,delay:450}),body(strands,'Innate pathways',{maskToken:true,delay:750})]);
add('halcyon-mists','Soothing ancestral mist',[body('ambient_fog.001.complete.small.white,smoke.puff.centered.grey','Soothing mist',{scale:1.3}),body('spirit_guardians.blueyellow.ring','Ancestral support',{opacity:.35,delay:450})]);
add('hallowed-ground','Life-infused ground',[field('ward.star.yellow.01','Hallowed ground',{below:true}),field('swirling_sparkles.01.blue','Vital ground',{delay:450})],{nativeArea:true,castingOnly:false});
add('halt-death','Hourglass invocation',[self('icosahedron.simple.blue','Hourglass focus',{scale:.65}),self(inward,'Sand gathered upward',{offsetY:-.35,scale:.65,delay:500}),self(shield,'Death ward petition',{scale:.5,delay:900})]);
add('harrowing','Harrow reading invocation',[body(signs,'Harrow ink symbols',{maskToken:true,scale:.85}),self(dice,'Cards read',{scale:.55,delay:400}),body(stars,'Fate contemplated',{offsetY:-.35,scale:.75,delay:900})]);
add('hasted-assault','Attack speed granted',[self('footprints.shoe.grey','Stride potential',{below:true,scale:.7}),self('energy_strands.02.marker.bluepurple','Quickened attack potential',{scale:.65,delay:550,opacity:.45})]);
add('haunting-spirit','Invisible haunting',[body('spirit_guardians.blueyellow.ring','Haunting presence',{opacity:.35}),body(horror,'Private spirit omen',{scale:.45,offsetY:-.35,delay:600})]);
add('haven-in-the-ether','Extradimensional haven invocation',[self(portal,'Haven entrance petition',{scale:1.2}),self(shield,'Attunement petition',{scale:.5,offsetY:-.15,delay:650})]);
add('healing-plaster','Restorative clay',[body('liquid.blob.blue','Clay plaster',{scale:.55,tint:'#c3ab84'}),body(heart,'Restorative substance',{scale:.4,delay:550})]);
add('hearts-desire','Desire illusions',[body(heart,'Greatest desires',{scale:.65,offsetY:-.35}),body(shimmer,'Desire images',{opacity:.65,delay:450})]);
add('heartbond','Affection bond invocation',[link(tether,'Affection bond',{opacity:.6}),body(heart,'Shared affection',{scale:.55,delay:400}),body('icosahedron.simple.blue','Bond token',{scale:.3,offsetY:.4,delay:850})]);
add('hedge-prison','Dense hedge cube',[body(vines,'Hedge walls rise',{scale:1.4}),body(plants,'Dense bushes',{scale:1.25,delay:500})]);
add('heinous-future','Fractured future mirror',[body(shimmer,'Fractured mirror',{scale:.9}),image('Possible future reflection',{copies:1,copySpread:0,opacity:.3,delay:300}),body(horror,'Dreadful possibility',{scale:.4,offsetY:-.4,delay:850})]);
add('helpful-reload','Weapon reload',[body('icosahedron.simple.blue','Ammunition at weapon',{scale:.25,offsetX:.45}),body('glint.yellow.few','Reload detail',{scale:.45,offsetX:.45,delay:450})]);
add('helpful-steps','Ladder or staircase',[self(shimmer,'Steps take shape',{scale:.8,offsetY:-.1}),self(glint,'Construction glints',{scale:.6,delay:300}),self(text,'Steps sketched',{scale:.75,delay:500})]);
add('heroic-feat','Martial knowledge',[self(text,'Combat technique recalled',{offsetY:-.35,scale:.7}),self('energy_strands.02.marker.bluepurple','Unchosen technique',{scale:.7,delay:550,opacity:.5})]);
add('heroism','Inner heroism',[body('ward.star.yellow.01','Heroic resolve',{scale:.8}),body(heart,'Courage',{scale:.45,offsetY:-.35,delay:600})]);
add('hidebound','Thick hide',[body('aura_themed.01.inward.complete.nature.01.green','Hide hardens',{maskToken:true}),body(shield,'Physical resistance',{scale:.55,delay:500})]);
add('holy-host','Holy army invocation',[self('ward.star.yellow.01','Holy host petition',{scale:1.1}),self('swirling_feathers.outburst.01.textured','Holy presence',{scale:1.2,delay:550}),self(signs,'Military choice',{scale:.6,delay:900})]);
add('honeyed-words','Smooth falsehoods',[self(text,'Smooth words',{offsetY:-.35,scale:.7}),self('liquid.blob.blue','Honeyed speech',{offsetY:-.1,scale:.35,tint:'#e1b54b',delay:600})]);
add('horde-of-underlings','Six underling spaces',[fan('energy_strands.02.marker.bluepurple','Underling invitations',{fanCount:6,scale:.35,opacity:.65})],{pattern:'coneObjectFan',nativeArea:true});
add('hot-air','Burning lungs',[body(fire,'Lungs burn',{maskToken:true,scale:.6}),body(sound,'Auditory heat',{offsetY:-.1,scale:.6,delay:500})],{castingOnly:false});
add('house-of-imaginary-walls','Mimed wall',[self('arcane_hand.blue','Wall pantomime',{scale:.6,offsetX:.45}),self('energy_strands.02.marker.bluepurple','Imaginary wall',{offsetX:.9,opacity:.18,scale:1.2,delay:350}),self(shimmer,'Mimed boundary',{offsetX:.9,scale:1.2,delay:650})]);
add('hungry-depths','Corrupted water vortex',[field('template_circle.vortex.loop.blue','Water spiral',{opacity:.7}),field(eyes,'Eyes in the depths',{scale:.65,below:false,delay:300}),field('bite.200px.red','Gnashing depths',{scale:.6,delay:650})],{nativeArea:true,castingOnly:false});
add('hunters-luck','Foe knowledge fortune',[self(eye,'Creature details recalled',{scale:.6,offsetY:-.35}),self(dice,'Knowledge fortune',{scale:.45,delay:550})]);
add('hunters-vision','Visible hunted prey',[body('hunters_mark.pulse.01','Prey glow',{scale:1.1,opacity:.6}),body(eye,'Shared prey vision',{scale:.45,offsetY:-.4,delay:550})]);
add('ibexs-harvest','Harvest tale',[self(notes,'Harvest tale told',{offsetY:-.4,scale:.6}),field(leaves,'Bountiful harvest',{opacity:.75,delay:550}),body(heart,'Shared bounty',{scale:.4,delay:800})]);
add('ideal-mimicry','Sympathetic doll invocation',[image('Target likeness',{copies:1,copySpread:0,scale:.45,offsetX:.7,opacity:.6}),self('liquid.splash02.red','Body component',{below:true,scale:.4,delay:350}),self(strands,'Doll bond petition',{scale:.6,offsetX:.7,delay:800})]);
add('ill-omen','Misfortune',[body(dice,'Unfavorable chance',{scale:.6}),body(fear,'Ill omen',{scale:.4,offsetY:-.35,delay:550})]);
add('illuminate','Light sources ignited',[field('dancing_light.yellow','Lights kindle',{scale:.9,opacity:.65}),field(glint,'Firelight glints',{delay:400})],{nativeArea:true});
add('illusory-creature','Unchosen creature illusion',[self(shimmer,'Creature image locus',{scale:1.2}),self(eye,'Illusory senses',{scale:.45,offsetY:-.5,delay:650})]);
add('illusory-object','Unchosen object illusion',[field(shimmer,'Stationary image',{opacity:.55}),field(signs,'Image locus',{scale:.25,delay:650})],{nativeArea:true});
add('imaginary-lockbox','Container stored in mind',[body('icosahedron.simple.blue','Container focus',{scale:.65,scaleOut:.1,scaleOutDuration:2000}),self(eye,'Mental lockbox',{scale:.45,offsetY:-.35,delay:600})]);
add('imaginary-weapon','Force weapon arc',[self('melee_attack.01.magic_sword.yellow.01','Force weapon arc',{scale:1}),body('energy_attack.01.blue','Force contact',{scale:.7,delay:450})],{castingOnly:false});
add('imitate-fauna','Animal disguise',[body(leaves,'Animal nature disguise',{maskToken:true}),body(shimmer,'Species appearance',{maskToken:true,opacity:.5,delay:450})]);
add('impaling-spike','Cold iron spike',[body('spike_trap.05x05ft.top.holes.normal.01.01','Iron spike rises',{scale:1.25,below:true}),body('aura_themed.01.outward.complete.metal.01.grey','Cold iron',{scale:.85,delay:350})],{castingOnly:false});
add('impeccable-flow','Cosmic order attunement',[self('icosahedron.rune.above.blueyellow','Cosmic order',{scale:.8}),self(strands,'Order attunement',{opacity:.5,delay:600})]);
add('implosion','Inward crushing force',[body(inward,'Crushing force',{scaleIn:1.5,scaleInDuration:1300,scale:.65}),body(voidField,'Collapse pressure',{scaleOut:.35,scaleOutDuration:1800,delay:250})],{castingOnly:false});
add('imprinting-hand','Hand imprint',[body('arcane_hand.blue','Hand presses',{scale:.65,offsetX:.15}),body('energy_strands.02.marker.bluepurple','Body imprint',{maskToken:true,scale:.6,delay:500})],{castingOnly:false});
add('imprisonment','Imprisonment invocation',[body(text,'Prison form described',{scale:.65,offsetY:-.35}),body(ward,'Prison form petition',{scale:.9,delay:450}),body('energy_strands.02.marker.bluepurple','Confinement focus',{scale:1.2,opacity:.4,delay:850})]);
add('incarnate-ancestry','Past ancestry invocation',[body(eye,'Past life contact',{scale:.55,offsetY:-.35}),body(text,'Ancestral memory',{scale:.8,delay:400}),body(strands,'Incarnation petition',{maskToken:true,opacity:.5,delay:900})]);
add('incarnate-shadow-minuet','Shadow dance',[self('drop_shadow','Shadow separates',{below:true,offsetX:.6,scale:1.1}),image('Dancing shadow',{subject:'source',copies:1,offsetX:.8,opacity:.4,tint:'#16131d',saturation:-1,delay:450}),self(notes,'Shadow minuet',{scale:.6,offsetX:.75,delay:700})]);
add('incendiary-aura','Combustible aura',[field('fumes.04.complete.grey','Combustible air',{opacity:.3}),self(fire,'Ignition potential',{scale:.45,opacity:.45,delay:650})],{nativeArea:true});
add('indestructibility','Cause and effect severed',[self(voidField,'Causality boundary',{scale:1.3,opacity:.5}),self(strands,'Connections sever',{scaleOut:.4,scaleOutDuration:2500,delay:550})]);
add('indolent-haze','Poppy scent',[field(petals,'Poppy petals',{opacity:.45}),field('sleep.cloud.01.pink','Soothing calm',{opacity:.5,delay:400})],{nativeArea:true});
add('inevitable-disaster','Future disaster seeded',[body(signs,'Cause and effect thread',{scale:.6}),body(dice,'Unknown disaster pending',{scale:.45,offsetY:-.4,delay:700})]);
add('infectious-comedy','Magical joke',[self(sound,'Joke spoken',{scale:.55,offsetY:-.1}),body(notes,'Laughter invitation',{scale:.65,offsetY:-.3,delay:450})]);
add('infinitesimal-collapse-field','Stretched spacetime',[field(voidField,'Space stretches',{opacity:.45}),field('energy_strands.02.marker.bluepurple','Temporal distortions',{opacity:.55,delay:450})],{nativeArea:true});
add('infuse-vitality','Vital attack empowerment',[body('ward.star.yellow.01','Vital energy',{scale:.75}),body('swirling_sparkles.01.blue','Strikes empowered',{maskToken:true,delay:600})]);
add('inner-upheaval','Focused qi attacks',[self(strands,'Qi focuses',{scale:.8}),self('unarmed_strike.magical.01.blue','Unarmed technique',{scale:1.1,delay:450})],{castingOnly:false});
add('inscrutable-mask','Shadow mask',[self('darkness.black','Mask of shadow',{scale:.55,offsetY:-.3,opacity:.55}),self(eyes,'Impenetrable features',{scale:.4,offsetY:-.35,delay:500,opacity:.35})]);
add('inside-ropes','Guts as rope',[self('liquid.splash02.red','Guts drawn forth',{offsetY:.15,scale:.55}),self(strands,'Gut rope',{scale:.9,tint:'#b8787f',rotation:90,delay:500})]);
add('instant-minefield','Hidden mines prepared',[self('fire_trap.01','Mine preparation',{scale:.6,opacity:.4}),self(signs,'Mine placement choice',{scale:.5,delay:650})]);
add('instant-parade','Illusory parade',[field(notes,'Parade music',{scale:.65}),field(shimmer,'Illusory crowd locus',{opacity:.55,delay:350}),self(sound,'Crowd noise',{offsetY:-.2,scale:.55,delay:650})],{nativeArea:true});
add('instant-pottery','Earthenware shaping',[self('liquid.blob.blue','Clay gathers',{scale:.6,tint:'#b78e65'}),self(inward,'Earthen material shapes',{scale:.65,delay:400,tint:'#b78e65'}),self(shimmer,'Simple pottery locus',{scale:.8,delay:800})]);
add('interdisciplinary-incantation','Borrowed spell formula',[self(particles,'Spell embers gathered',{scale:.7}),self(text,'Formula studied',{offsetY:-.35,scale:.75,delay:550})]);
add('interstellar-void','Frigid outer space',[body('darkness.black','Freezing void',{opacity:.55}),body(frost,'Interstellar chill',{delay:450}),body(stars,'Distant stars',{scale:1.1,delay:650})],{castingOnly:false});
add('inveigle','Friendship invocation',[body(heart,'Friendship petition',{offsetY:-.2,scale:.6}),body('liquid.blob.blue','Attuned oils',{below:true,scale:.65,delay:600}),body(text,'Suggestions framed',{scale:.65,delay:900})]);
add('invisibility-cloak','Invisible cloak',[self(shimmer,'Cloak fades',{maskToken:true,opacity:.45}),image('Fading silhouette',{subject:'source',copySpread:0,opacity:.35,alphaOut:true,delay:350})]);
add('invisibility-curtain','Invisible boundary',[self('energy_strands.02.marker.bluepurple','Curtain boundary',{opacity:.3,scale:1.5}),self(shimmer,'One-sided concealment',{scale:1.1,opacity:.3,delay:600})]);
add('invisible-item','Invisible object',[body(shimmer,'Object fades',{maskToken:true,scale:.7,opacity:.45}),body(inward,'Invisible outline',{scale:.7,opacity:.3,delay:400})]);
add('invoke-the-crimson-oath','Ruby energy arc',[self('melee_attack.01.trail.01.orangered','Crimson weapon arc',{scale:1}),fan('energy_field.01.blue','Ruby blast',{fanCount:7,tint:'#c41e44',scale:.55,delay:450})],{pattern:'coneObjectFan',nativeArea:true,castingOnly:false});
add('invoke-the-harrow','Harrow card influence',[self(dice,'Harrow suit drawn',{scale:.55}),body(signs,'Card influence',{scale:.65,delay:500})]);
add('invoke-true-name','True name spoken',[self(sound,'True name',{scale:.5,offsetY:-.15}),body(text,'Name revealed',{scale:.65,offsetY:-.35,delay:450})]);
add('iron-gut','Elastic metal stomach',[self('aura_themed.01.inward.complete.metal.01.grey','Stomach toughens',{maskToken:true,scale:.65,offsetY:.15}),self('icosahedron.simple.blue','Storage capacity',{scale:.35,offsetY:.25,delay:600})]);
add('isolation','Loneliness cloak',[body('darkness.black','Loneliness cloaks',{opacity:.5}),body('icon.mute.dark_red','Isolation symbol',{scale:.45,offsetY:-.4,delay:550})]);
add('it-is-written','Destiny envisioned',[self(text,'Destiny written',{scale:.7,offsetY:-.35}),self(stars,'Future certainty',{scale:.9,delay:650})]);
add('item-facade','Object condition illusion',[body(shimmer,'Surface condition illusion',{maskToken:true}),body(signs,'Unchosen finish',{scale:.45,delay:650})]);
add('jassims-allegiance','Jassim invocation',[self('aura_themed.01.inward.complete.metal.01.grey','Automaton invitation',{scale:1.2}),self(eyes,'Metal and glass eyes',{offsetY:-.4,scale:.7,delay:650}),self('ground_cracks.01.orange','Jassim locus',{below:true,delay:950})]);
add('jealous-hex','Jealousy curse',[body(fear,'Jealous desire',{scale:.5,offsetY:-.3}),body('energy_strands.02.marker.bluepurple','Attribute curse',{maskToken:true,delay:650})]);
add('kaiju-ward','Structure ward invocation',[body(shield,'Structure protection petition',{scale:.85}),body('aura_themed.01.inward.complete.metal.01.grey','Structure reinforcement',{opacity:.45,delay:650})]);
add('kgalaserkes-axes','Legendary axes tale',[self(notes,'Kgalaserke tale',{scale:.6,offsetY:-.35}),body('handaxe.melee','Axes remembered',{scale:.65,opacity:.5,delay:550}),body(heart,'Martial resolve',{scale:.4,delay:850})]);
add('ki-cutting-sight','Qi scrutiny',[self(eye,'Qi flow studied',{offsetY:-.35,scale:.55}),body(strands,'Qi junctions',{opacity:.55,scale:.8,delay:500})]);
add('know-the-enemy','Creature knowledge',[self(text,'Creature facts recalled',{scale:.7,offsetY:-.3}),self(eye,'Enemy understanding',{scale:.45,offsetY:-.5,delay:550})]);
add('labyrinthine-prison','Twisted maze invocation',[body(signs,'Maze sketched',{scale:1.1}),body('energy_strands.02.marker.bluepurple','Twisted space petition',{scale:1.25,delay:650}),body(eye,'Maze focus',{scale:.4,delay:950})]);
add('last-nights-vigil','Overnight vigil',[self('fumes.steam','Incense remains lit',{scale:.55,offsetY:-.35}),body(heart,'Loved one petition',{scale:.5,delay:500}),self(snow,'Winter vigil',{scale:.35,offsetY:-.75,delay:1000})]);
add('lifes-fresh-bloom','Sparkling flowers',[field(plants,'Grass and shrubs bloom'),field(petals,'Flowers open',{delay:500}),field(glint,'Sparkling growth',{delay:850})],{nativeArea:true});
add('lignify','Flesh turning to wood',[body('aura_themed.01.inward.complete.wood.01.green','Wood enters flesh',{maskToken:true}),body(leaves,'Wooden texture',{maskToken:true,scale:.8,delay:600})]);
add('lingering-composition','Composition flourish',[self(notes,'Musical flourish',{scale:.75,offsetY:-.35}),self(sound,'Composition extends',{scale:.65,playbackRate:.7,delay:450}),self(notes,'Flourish tail',{scale:.4,offsetX:.55,offsetY:-.55,delay:900})]);
add('linnorm-sting','Fiery venom bite',[body('bite.200px.red','Linnorm bite',{scale:.7}),body(poison,'Venom offered',{scale:.45,delay:400}),body(fire,'Fiery venom',{scale:.65,opacity:.55,delay:700})],{castingOnly:false});
add('live-wire','Copper current filament',[link('electric_arc','Charged copper wire',{scale:.45}),body('aura_themed.01.outward.complete.metal.01.grey','Sharp copper',{scale:.65,delay:350})],{pattern:'tetherConnection',castingOnly:false});
add('living-graveyard','Graveyard thrall',[self('ground_cracks.01.orange','Graveyard ground',{below:true,scale:1.2}),self('melee_attack.02.bone.01','Grave remains',{scale:.9,delay:450}),self(skull,'Graveyard spirit locus',{scale:.65,offsetY:-.3,delay:750})]);
add('localized-quake','Ground shaking',[self('ground_cracks.02.orange','Ground tremor',{below:true,scale:1.5}),self(sound,'Quake pulse',{below:true,scale:1.4,delay:350})],{castingOnly:false});
add('loose-times-arrow','Time stream plucked',[self(strands,'Time stream plucked',{offsetX:.35,scale:.7}),link(tether,'Time string',{scale:.45,delay:350}),body('footprints.shoe.grey','Movement potential',{below:true,scale:.75,delay:750})],{pattern:'tetherConnection'});
add('loremasters-etude','Muse knowledge',[self(notes,'Muse invocation',{scale:.6,offsetY:-.35}),body(text,'Knowledge recalled',{scale:.7,delay:500}),body(dice,'Recall fortune',{scale:.4,delay:850})]);
add('lose-the-path','Shifting terrain illusion',[body(shimmer,'Terrain perception shifts',{opacity:.55}),body('footprints.shoe.grey','Misleading route',{below:true,scale:.8,delay:550})]);
add('lotus-walk','Watery plants at feet',[self(plants,'Lotus blooms',{below:true,offsetY:.35,scale:.9}),self(petals,'Watery petals',{below:true,offsetY:.35,scale:.75,delay:500}),self(splash,'Water surface',{below:true,scale:1.05,delay:700})]);
add('loyaltys-ward','Room talisman invocation',[self(ward,'Opening talismans',{scale:.9}),self(shield,'Room ward petition',{scale:.6,delay:650}),self(text,'Selected criteria',{scale:.6,delay:900})]);
add('lucky-break','Saving throw reroll',[self(dice,'Second chance',{scale:.65}),self(glint,'Fortune glints',{scale:.65,delay:500})]);
add('lucky-month','Lucky token invocation',[body('icosahedron.simple.blue','Token focus',{scale:.4,offsetY:.25}),body(dice,'Luck petition',{scale:.65,delay:550}),body(stars,'Monthly fortune',{scale:.8,delay:900})]);
add('lucky-number','Lucky number prepared',[self(dice,'Number drawn',{scale:.65}),self(rune,'Lucky number seal',{scale:.5,offsetY:-.35,delay:650})]);
add('lure-dream','Animate dream invitation',[self('sleep.cloud.01.pink','Dream realm beckons',{scale:1.1}),self(eye,'Dream presence locus',{scale:.55,offsetY:-.3,delay:650})]);
add('luring-wail','Plaintive cry',[self(sound,'Plaintive wail',{offsetY:-.15,scale:.7}),field(sound,'Call fills the air',{delay:300,opacity:.6}),field('icon.music_note.blue','Luring call symbol',{scale:.2,delay:750})],{nativeArea:true});
add('mad-monkeys','Monkey spirits',[field('particles.002.001.complete.many.orangeyellow,particles.002.001.complete.many.blue','Monkey spirits scramble',{opacity:.75,tint:'#c99a5b'}),field('footprints.monster.grey,footprints.shoe.grey','Climbing monkey marks',{scale:.6,delay:500})],{nativeArea:true});
add('magic-passage','Wall tunnel',[body(portal,'Tunnel entrance',{scale:1.25}),body(inward,'Wall space opens',{scale:1.1,delay:500})]);
add('magic-stone','Vital stones',[body('falling_rocks.top.1x1.grey','Stones prepared',{scale:.35}),body('ward.star.yellow.01','Vitality infused',{scale:.65,delay:550})]);
add('magics-vessel','Divine receptacle',[body(inward,'Pure magic gathers',{maskToken:true}),body(shield,'Divine receptacle',{scale:.6,delay:550}),body(strands,'Spell energy capacity',{opacity:.55,delay:900})]);
add('magnetic-dominion','Roiling magnetic fields',[field('aura_themed.01.orbit.complete.metal.01.grey','Magnetic fields',{opacity:.75}),field(inward,'Magnetic control',{opacity:.5,delay:450})],{nativeArea:true});
add('malediction','Distress emanation',[self(fear,'Distress spoken',{scale:.45,offsetY:-.35}),field('energy_strands.02.marker.bluepurple','Distress field',{opacity:.5,delay:400}),field('icon.shield_cracked.purple','Defense unease',{scale:.25,delay:850})],{nativeArea:true});
add('manifest-will','Patron connection released',[self(strands,'Broken patron connection',{scaleOut:.6,scaleOutDuration:1800}),field(signs,'Manifest will',{delay:450,opacity:.55})],{nativeArea:true});
add('manifestation','Unchosen spell potential',[self(text,'Magic secrets shaped',{scale:.7,offsetY:-.3}),self('energy_strands.02.marker.bluepurple','Unchosen power',{scale:1.15,opacity:.55,delay:650})]);
add('mariners-curse','Roiling sea curse',[body(splash,'Sea curse',{scale:1.05}),body(poison,'Seasickness omen',{scale:.45,offsetY:-.3,delay:550})]);
add('mark-of-blood','Blood on weapon',[self('liquid.splash02.red','Blood placed on weapon',{scale:.4,offsetX:.4}),self('icon.drop.red','Life essence charged',{scale:.35,offsetX:.4,delay:550})]);
add('marvelous-mount','Unchosen fantastical mount',[body('footprints.shoe.grey','Mount invitation',{below:true,scale:1.3}),body(shimmer,'Mount locus',{scale:1.5,opacity:.6,delay:650})]);
add('medusas-wrath','Petrifying unarmed strike',[self('unarmed_strike.magical.01.blue','Medusa power strike',{scale:1.05}),body('aura_themed.01.inward.complete.metal.01.grey','Petrifying potential',{maskToken:true,opacity:.5,delay:550})],{castingOnly:false});
add('menacing-lament','Threatening dirge',[self(notes,'Dirge sung',{offsetY:-.35,scale:.75}),field(sound,'Menacing lament',{opacity:.6,delay:350})],{nativeArea:true});
add('metal-reverberation','Tuning fork vibration',[self('quarterstaff.melee','Tuning fork symbol',{scale:.45,offsetX:.4,rotation:90}),body(sound,'Metal note',{scale:.9,delay:450}),body('aura_themed.01.orbit.complete.metal.01.grey','Reverberating metal',{scale:.75,delay:650})],{castingOnly:false});
add('metallic-meteorite-glyph','Meteor-seeking rune',[body(rune,'Meteor glyph',{scale:.6}),object('celestial_bodies.asteroid.single.iron.red.01','Metal meteor',{delay:500,scale:.6,playbackRate:3}),body('aura_themed.01.outward.complete.metal.01.grey','Meteor pressure',{delay:950,scale:1.15})],{pattern:'object',castingOnly:false});
add('mimic-spell','Observed spell knowledge',[self(eye,'Spell watched',{offsetY:-.35,scale:.55}),self(text,'Spell secrets retained',{scale:.8,delay:600})]);
add('mind-games','Mental contest',[link(tether,'Minds contend',{scale:.5}),body(stun,'Mental pressure',{scale:.45,offsetY:-.3,delay:550})],{pattern:'tetherConnection'});
add('mind-probe','Memory questioning',[link(tether,'Thoughts enter',{scale:.45}),body(eye,'Memories sifted',{offsetY:-.35,scale:.55,delay:450}),body(text,'Question locus',{scale:.7,delay:800})],{pattern:'tetherConnection'});
add('mind-swap','Mind exchange invocation',[link(tether,'Exchange petition',{opacity:.6}),body(eye,'Mind compatibility',{offsetY:-.35,scale:.55,delay:400}),self(eye,'Second mind focus',{offsetY:-.35,scale:.55,delay:750})]);
add('mindscape-door','Mindscape entry invocation',[self('sleep.cloud.01.pink','Mindscape concentration',{opacity:.55}),self(portal,'Mindscape door petition',{scale:1.1,delay:700})]);
add('mindscape-shift','Adjacent mindscape invocation',[self('energy_strands.02.marker.bluepurple','Corresponding location focus',{scale:1.1}),self('sleep.cloud.01.pink','Mindscape transport petition',{scale:1.2,opacity:.55,delay:650})],{descriptionSource:'gm'});
add('miracle','Divine aid requested',[self('ward.star.yellow.01','Divine source petition',{scale:1.1}),self(text,'Request offered',{scale:.65,offsetY:-.3,delay:650})]);
add('mirror-malefactors','Illusory mirrors',[body(shimmer,'Mirrors shimmer',{scale:1.4}),image('Hostile reflections',{copies:3,copySpread:.65,opacity:.5,delay:350}),body(horror,'Mental confrontation',{scale:.4,offsetY:-.3,delay:850})],{castingOnly:false});
add('moonlight-bridge','Moonlight span',[field('moonbeam','Radiant moonlight span',{areaLayout:'tiles',opacity:.7}),field(shimmer,'Shimmering bridge',{areaLayout:'tiles',opacity:.45,delay:500})],{delivery:'line',areaLayout:'tiles',previewArea:{type:'line',value:120,width:10,details:'10 feet wide and up to 120 feet long'}});
add('morass-of-ages','Temporal eddies',[field('template_circle.vortex.loop.blue','Time eddies',{playbackRate:.6,opacity:.6}),field(voidField,'Time draws out',{opacity:.4,delay:500})],{nativeArea:true});
add('mosquito-blight','Insect hive invocation',[self('particles.002.001.complete.few.blue','Hive insect symbols',{scale:.75,opacity:.6}),self(poison,'Disease petition',{scale:.55,delay:650})]);
add('mothers-blessing','Egg purification invocation',[self(water,'Eggs washed',{scale:.65}),self('icosahedron.simple.blue','Clutch focus',{below:true,scale:.7,delay:400}),self(particles,'Warm sand',{below:true,tint:'#c5a77d',delay:800})]);
add('movanic-glimmer','Animal awareness',[body(eye,'Awareness opens',{offsetY:-.35,scale:.55}),body(leaves,'Animal understanding',{opacity:.55,delay:600})]);
add('mud-pit','Clinging mud',[field('grease.dark_brown.loop','Thick mud',{opacity:.9}),field('liquid.blob.blue','Mud clings',{tint:'#70553f',opacity:.45,delay:400})],{nativeArea:true});
add('mushroom-patch','Mushroom spores',[field(plants,'Fungal growth symbols',{below:true}),field('particles.002.001.complete.few.blue','Irritating spores',{opacity:.65,delay:600})],{nativeArea:true});
add('mystic-beacon','Next spell empowered',[body('dancing_light.blueyellow','Mystic beacon',{offsetY:-.5,scale:.55}),body('energy_strands.02.marker.bluepurple','Spell potential',{scale:.9,delay:600})]);
add('mystic-carriage','Carriage invocation',[self('fumes.steam','Incense burnt',{scale:.65,offsetY:-.25}),self('swirling_feathers.outburst.01.textured','Feather offering',{scale:.75,delay:400}),self('footprints.shoe.grey','Destination named',{below:true,scale:.9,delay:800})]);
add('necrotic-radiation','Slow necrotic radiation',[body(voidField,'Necrotic radiation',{opacity:.5}),body(skull,'Void locus',{scale:.4,delay:650})]);
add('necrotize','Localized putrefaction',[body('aura_themed.01.inward.complete.nature.01.green','Flesh decay',{maskToken:true,opacity:.6}),body(skull,'Necrosis focus',{scale:.5,delay:450})],{castingOnly:false});
add('never-mind','Mental faculties curse',[body(text,'Thought symbols dim',{offsetY:-.3,scale:.7,alphaOut:true}),body(stun,'Mental impairment omen',{scale:.45,offsetY:-.4,delay:600})]);
add('nightmare','Nightmares prepared',[self('sleep.cloud.01.pink','Dream connection',{scale:.8}),self(horror,'Nightmare sent',{scale:.55,offsetY:-.35,delay:650})]);
add('nudge-the-odds','Golden luck feature',[self(dice,'Games fortune',{scale:.6}),self(glint,'Golden facial detail',{scale:.45,offsetY:-.3,delay:600})]);
add('nymphs-grace','Unearthly beauty mask',[self(petals,'Apparition beauty',{scale:.7,offsetY:-.3}),field(shimmer,'Bewildering beauty aura',{opacity:.5,delay:400})],{nativeArea:true});
add('nymphs-token','Favor token',[self(petals,'Flower favor',{scale:.45,offsetX:.35}),self(heart,'Token of favor',{scale:.35,offsetX:.35,delay:600})]);
add('oaken-resilience','Bark skin',[body('aura_themed.01.inward.complete.wood.01.green','Bark consistency',{maskToken:true}),body(shield,'Oaken resilience',{scale:.6,delay:600})]);
add('oathkeepers-insignia','Promise trinket',[self('icosahedron.simple.blue','Promise token',{scale:.4,offsetX:.35}),self(text,'Terms recorded',{scale:.6,offsetY:-.35,delay:600})]);
add('oblivious-expulsion','Memory removal invocation',[body(text,'Cult memory focus',{scale:.7,offsetY:-.35}),body(eye,'Memory severance petition',{scale:.55,offsetY:-.5,delay:650}),body(inward,'Memory ritual',{opacity:.4,delay:950})]);
add('oceans-roar','Water consciousness invocation',[self(splash,'Water spirit petition',{scale:1.4,below:true}),self(eye,'Consciousness invoked',{scale:.6,delay:500}),self(sound,'Ocean invocation',{scale:1.1,delay:850})]);
add('ocular-overload','Vision reaction prepared',[self(eye,'Vision trigger prepared',{scale:.6,offsetY:-.35}),self('swirling_sparkles.01.blue','Illusions held',{scale:.8,opacity:.45,delay:600})]);
add('ode-to-ouroboros','Death delayed by song',[self(notes,'Death-defying ode',{scale:.7,offsetY:-.35}),body(heart,'Life held',{scale:.55,delay:500}),body('ward.star.yellow.01','Death threshold ward',{scale:.7,delay:850})]);
add('oil-slicked-walls','Wall oil invocation',[self('grease.dark_brown.loop','Oil prepared',{scale:.85,below:true}),self(shimmer,'Wall treatment petition',{scale:1.1,opacity:.45,delay:650})]);
add('omnidirectional-scan','Many viewing angles',[self(eyes,'Viewing angles',{scale:.8,offsetY:-.25}),field(pulse,'Surroundings scanned',{opacity:.25,delay:400})],{nativeArea:true});
add('one-with-the-land','Merged natural feature',[self('aura_themed.01.inward.complete.nature.01.green','Natural feature meld',{maskToken:true}),self(leaves,'Terrain union',{scale:1.2,opacity:.55,delay:450}),self(pulse,'Tremorsense',{below:true,scale:1.2,opacity:.3,delay:850})]);
add('open-the-wall-of-ghosts','Spirit barrier invocation',[self('spirit_guardians.blueyellow.ring','Barrier spirits addressed',{opacity:.45}),self('ward.star.yellow.01','Quiet passage petition',{scale:.8,delay:650}),self(fog,'Misty barrier focus',{scale:1.1,opacity:.4,delay:900})],{descriptionSource:'gm'});
add('orb-of-twisting-fate','Forehead fate orb',[body('bubble.001.001.complete.blue','Glass orb',{scale:.45,offsetY:-.35}),body(dice,'Alternative choices',{scale:.5,offsetY:-.6,delay:600})]);
add('ordained-purpose','Cosmic authority',[self('icosahedron.rune.above.blueyellow','Order invoked',{scale:.8}),field(signs,'Purpose imposed',{opacity:.6,delay:400}),field(horror,'Remorse symbol',{scale:.25,delay:850})],{nativeArea:true,castingOnly:false});
add('osseous-cage','Bone prison',[field('melee_attack.02.bone.01','Bone cage bars',{scale:1.2}),field('energy_strands.02.marker.bluepurple','Prison boundary',{opacity:.4,delay:500})],{nativeArea:true});
add('outcasts-curse','Off-putting presence',[body('energy_strands.02.marker.bluepurple','Abrasive presence',{opacity:.55}),body(fear,'Social misfortune',{scale:.45,offsetY:-.35,delay:600})]);
add('overflowing-sorrow','Spreading sadness',[self('icon.drop.red','Sorrow symbol',{offsetY:-.35,scale:.45,tint:'#79a0bb'}),field('energy_field.01.blue','Sorrow spreads',{opacity:.45,delay:350})],{nativeArea:true});
add('overselling-flourish','Theatrical injury',[self('liquid.splash02.red','Theatrical blood',{scale:1.05}),self(sound,'Anguished scream',{offsetY:-.15,scale:.65,delay:350}),self(notes,'Grand spectacle',{scale:.55,delay:650})]);
add('overwhelming-presence','Supernatural splendor',[self('ward.star.yellow.01','Majestic presence',{scale:1.2}),self(glint,'Supernatural splendor',{scale:1.4,delay:400}),field(signs,'Regalia impression',{opacity:.45,delay:750})],{nativeArea:true});
add('owb-pact','Owb petition',[self('darkness.black','Owb invitation',{scale:1.1,opacity:.55}),self(text,'Goal and bargain',{scale:.7,delay:650}),self(eye,'Owb attention',{scale:.5,offsetY:-.4,delay:900})]);
add('pack-attack','Pack coordination',[link(tether,'Pack connection',{scale:.45}),body('footprints.shoe.grey','Coordinated positions',{below:true,scale:.85,delay:600})],{pattern:'tetherConnection'});
add('pack-breaker','Allegiance mistrust',[body(eye,'Allies misperceived',{offsetY:-.35,scale:.6}),body('markers.chain.spectral_standard.complete.02.blue','Allegiance frays',{scaleOut:.35,scaleOutDuration:2000,delay:500})]);
add('pain-of-ages','Stored spiritual anguish',[field('spirit_guardians.blueyellow.ring','Old anguish released',{opacity:.65}),field(horror,'Calamity echoes',{scale:.35,delay:500})],{nativeArea:true,castingOnly:false});
add('palm-held-sun','Miniature star',[self('dancing_light.yellow','Miniature star',{scale:.55,offsetX:.4,offsetY:-.1}),self('fire_ring.500px.red','Solar glow',{scale:1.3,opacity:.5,delay:400})]);
add('paranoia','Threat perception',[body(eyes,'Everywhere threats',{offsetY:-.2,scale:.85}),body(fear,'Intense suspicion',{offsetY:-.45,scale:.4,delay:550})]);
add('parch','Dehydrating winds',[body('wind_lines.01.01.white','Dry winds',{scale:1.1,tint:'#cfb899'}),body('icon.drop.red','Moisture ebbs',{scale:.4,delay:600,alphaOut:true})]);
add('path-of-least-resistance','Three possible routes',[self('footprints.shoe.grey','Possible route',{below:true,offsetX:-.75,opacity:.4}),self('footprints.shoe.grey','Possible route',{below:true,offsetY:.75,opacity:.4}),self('footprints.shoe.grey','Possible route',{below:true,offsetX:.75,opacity:.4}),self(eye,'Safest route contemplated',{offsetY:-.35,scale:.55,delay:650})]);
add('patrons-puppet','Familiar command',[self(strands,'Patron command',{offsetY:-.25,scale:.85}),self(signs,'Familiar agency',{scale:.5,delay:650})]);
add('peer-into-the-past','Historical scene invocation',[self(eye,'Past moment focus',{scale:.55,offsetY:-.35}),self(text,'Scene recalled',{scale:.85,delay:450}),self(shimmer,'Frozen scene petition',{scale:1.3,opacity:.5,delay:850})]);
add('penumbral-disguise','Shadows mask features',[body('darkness.black','Features shadowed',{scale:.85,maskToken:true,opacity:.45}),body(mist,'Penumbral outline',{scale:1.05,opacity:.5,delay:500})]);
add('perceive-the-threads-of-fate','Visible fate threads',[self(eyes,'Grand design viewed',{offsetY:-.25,scale:.75}),self(strands,'Tangled fate threads',{scale:1.3,delay:550})]);
add('perfect-strike','Recovered accuracy',[self(eye,'Strike accuracy recalled',{offsetY:-.35,scale:.5}),self('unarmed_strike.magical.01.blue','Unarmed technique renewed',{scale:.8,delay:550,opacity:.5})]);
add('perfected-body','Bodily perfection',[self('aura_themed.01.inward.complete.nature.01.green','Body withstands',{maskToken:true}),self(shield,'Bodily resilience',{scale:.55,delay:600})]);
add('perfected-mind','Distractions removed',[self(stun,'Distractions focused',{scale:.5,offsetY:-.35,alphaOut:true}),self(eye,'Mind centers',{scale:.6,offsetY:-.35,delay:650})]);
add('perfected-thrall','Dense muscle thrall',[self('liquid.splash02.red','Muscle and blood locus',{scale:1.2}),self('melee_attack.02.bone.01','Hardened bone',{scale:.9,delay:400}),self('spirit_guardians.blueyellow.ring','Warrior spirit invitation',{scale:1.2,delay:800,opacity:.55})]);
add('perfection-of-essence','Immortality preparation',[self(water,'Final potion focus',{offsetY:.25,scale:.55}),self(poison,'Poison ordeal invoked',{scale:.5,delay:500}),self(text,'Anathema contemplated',{offsetY:-.35,scale:.7,delay:900})]);
add('perseiss-precautions','Ambush precautions',[body(eye,'Danger vigilance',{offsetY:-.35,scale:.6}),body(shield,'Ambush precaution',{scale:.65,delay:600})]);
add('persistent-servant','Chore servant invitation',[field('arcane_hand.blue','Servant task locus',{scale:.2,opacity:.6}),field(text,'Repeated chore instruction',{scale:.2,delay:650})],{nativeArea:true});
add('personal-blizzard','Scouring ice',[body('sleet_storm.01.blue','Personal blizzard',{scale:1.2}),body(frost,'Scouring ice',{scale:.95,delay:550})],{castingOnly:false});
add('personal-ocean','Seawater shroud',[self('bubble.001.001.complete.blue','Seawater bubble',{scale:1.3}),self(water,'Water fills space',{maskToken:true,opacity:.5,delay:450})]);
add('personal-rain-cloud','Overhead rain',[body('fog_cloud.01.white','Overhead cloud',{scale:.7,offsetY:-.8,opacity:.65}),body('template_square.raindrops.001.5x5.instant.combined.blue,sleet_storm.01.blue','Falling rain',{scale:1,offsetY:0,delay:550,opacity:.8})]);
add('petal-storm','Razor petals',[field(petals,'Petal storm',{opacity:.9}),field(leaves,'Petals churn',{delay:500,tint:'#efa8d1'})],{nativeArea:true});
add('phantasmagoria','Colliding dream images',[body('sleep.cloud.02.pink','Dream images collide',{scale:1.3}),body(eyes,'Many imagined lives',{scale:.9,delay:450}),body(text,'Information rush',{scale:.8,delay:800})],{castingOnly:false});
add('phantasmal-custodians','Custodian invocation',[self('arcane_hand.blue','Custodian tasks petition',{scale:.8,opacity:.5}),self(text,'Basic tasks assigned',{scale:.7,delay:650}),self(shimmer,'Entities invited',{scale:1.3,opacity:.45,delay:1000})]);
add('phantasmal-protagonist','Literary character image',[self(text,'Character recalled',{scale:.75,offsetY:-.35}),self(shimmer,'Protagonist image locus',{scale:1.3,opacity:.6,delay:550}),self(signs,'Theme choice',{scale:.55,delay:900})]);
add('phantasmal-treasure','Unchosen precious image',[body(heart,'Precious desire',{scale:.5,offsetY:-.3}),body('swirling_sparkles.01.blue','Treasure illusion locus',{scale:1.15,opacity:.6,delay:600})]);
add('phantom-orchestra','Ephemeral symphony',[field(notes,'Silhouetted instruments',{opacity:.75}),field(sound,'Orchestra crescendo',{delay:450}),field('wind_lines.01.01.white','Captured breezes',{opacity:.4,delay:800})],{nativeArea:true,castingOnly:false});
add('phantom-prison','Private illusory walls',[body('energy_strands.02.marker.bluepurple','Illusory walls',{scale:1.45,opacity:.55}),body(shimmer,'Private prison image',{scale:1.25,opacity:.45,delay:550})]);
add('phantom-ship','Ship spirit invocation',[body('spirit_guardians.blueyellow.ring','Undead crew bond petition',{opacity:.45}),body(shimmer,'Incorporeal ship petition',{maskToken:true,opacity:.4,delay:650}),body(splash,'Water connection',{below:true,scale:1.2,delay:900})]);
add('phase-familiar','Familiar becomes ghostly',[body(shimmer,'Familiar phases',{maskToken:true,opacity:.45}),image('Ghostly familiar',{copySpread:0,opacity:.3,saturation:-1,delay:400}),body(shield,'Phasing protection',{scale:.45,delay:850})]);
add('pied-piping','Enrapturing performance',[self(notes,'Piping melody',{scale:.75,offsetY:-.3}),self(sound,'Listeners beckoned',{scale:1.5,opacity:.6,delay:450})]);
add('pillar-of-water','Clear water cylinder',[self(water,'Water pillar locus',{scale:1.3,opacity:.65}),self('bubble.001.001.complete.blue','Self-contained water',{scale:1.4,opacity:.5,delay:600})]);
add('plague-shot','Ammunition disease invocation',[body(poison,'Disease infusion petition',{scale:.6}),body('glint.yellow.few','Ammunition green glow',{scale:.8,tint:'#7eaa5c',delay:650})]);
add('planar-collision','Elemental plane collision',[field('energy_field.01.blue','Planar collision',{opacity:.7}),field('energy_strands.02.marker.bluepurple','Unchosen plane fragment',{delay:450,scale:.8}),field('ground_cracks.02.orange','Terrain disruption',{below:true,opacity:.55,delay:850})],{nativeArea:true,castingOnly:false});
add('planar-displacement','Planar travel invocation',[self(ward,'Ritual circle drawn',{below:true,scale:1.3}),self(text,'Destination knowledge',{scale:.7,offsetY:-.35,delay:600}),self(strands,'Planar crossing petition',{scale:1.3,opacity:.5,delay:900})]);
add('planar-palace','Extradimensional entrance',[self(portal,'Dwelling entrance',{scale:1.1}),self(shimmer,'Demiplane door shimmer',{scale:.85,offsetX:.1,delay:550})]);
add('planar-seal','Planar barrier',[field('bubble.001.001.complete.blue','Visible planar barrier',{opacity:.6}),field(ward,'Planar travel seal',{scale:.4,delay:650})],{nativeArea:true});
add('planar-servitor','Divine servitor petition',[self('ward.star.yellow.01','Divine aid petition',{scale:1.1}),self(text,'Task and payment',{scale:.75,offsetY:-.3,delay:650}),self(shimmer,'Unchosen servitor locus',{opacity:.4,scale:1.1,delay:950})]);
add('plant-growth','Plant health invocation',[self(plants,'Crop growth petition',{below:true,scale:1.2}),self(leaves,'Healthy foliage',{scale:1.1,delay:650}),self(splash,'Plants nourished',{below:true,opacity:.4,delay:1000})]);
add('pocket-library','Extradimensional knowledge',[self(text,'Library knowledge prepared',{scale:.85,offsetY:-.35}),self('portals.vertical.ring','Library access',{scale:.45,offsetX:.4,delay:650})]);
add('pollen-pods','Wooden bulbs prepared',[self('icosahedron.simple.blue','Wooden pod focus',{below:true,scale:.55,tint:'#938664'}),self(plants,'Cultivated bulbs',{below:true,scale:.8,delay:550}),self(poison,'Stored toxic pollen',{scale:.35,delay:900})]);
add('portrait-of-spite','Blood portrait invocation',[image('Healthy portrait likeness',{copies:1,copySpread:0,offsetX:.7,scale:.7,opacity:.55}),self('liquid.splash02.red','Blood paint',{scale:.55,offsetX:.7,delay:400}),self(text,'Grievances recited',{scale:.75,offsetY:-.3,delay:850})]);
add('portrait-of-the-artist','Artist disguise',[self(shimmer,'Artist appearance',{maskToken:true}),self(text,'Unchosen craft illusion',{scale:.85,delay:550}),self(eye,'Artist impression',{scale:.5,offsetY:-.35,delay:850})]);
add('possession','Mind and soul transfer',[link(tether,'Mind and soul reach',{scale:.5}),body('spirit_guardians.blueyellow.ring','Possession attempt',{opacity:.5,delay:550}),self(eye,'Shared senses',{scale:.45,offsetY:-.35,delay:850})],{pattern:'tetherConnection'});
add('power-of-the-beasts','Beast strength invocation',[self(water,'Bone soup focus',{scale:.6,offsetY:.2}),self('melee_attack.02.bone.01','Powdered bones',{scale:.6,delay:450}),self('footprints.shoe.grey','Beast understanding petition',{below:true,scale:.95,delay:850})]);
add('power-word-blind','Blinding word',[self(sound,'Word of power',{scale:.55,offsetY:-.15}),body(eye,'Sight overwhelmed',{scale:.55,offsetY:-.35,delay:450}),body(glint,'Visual overload',{scale:.75,delay:700})]);
add('power-word-stun','Stunning word',[self(sound,'Word of power',{scale:.55,offsetY:-.15}),body(stun,'Mind overwhelmed',{scale:.6,offsetY:-.35,delay:450})]);
add('pressure-zone','Air pressure drop',[field('wind_lines.01.01.white','Pressure falls',{opacity:.45}),field(voidField,'Pressure zone',{opacity:.35,delay:550})],{nativeArea:true});
add('primal-call','Faerie circle invocation',[self(ward,'Faerie circle focus',{below:true,scale:1.1}),self(leaves,'Faerie circle offerings',{below:true,scale:1.2,delay:300}),self(plants,'Nature aid petition',{below:true,delay:650}),self(text,'Requested assistance',{scale:.65,delay:1000})]);
add('primal-chorus','Animal chorus call',[self(sound,'Primal howl',{scale:1.25,offsetY:-.1}),self('footprints.shoe.grey','Animals invited',{below:true,scale:.9,delay:500}),self(notes,'Chorus awaits',{scale:.7,delay:850})]);
add('primal-phenomenon','Natural intercession',[self(leaves,'Nature petition',{scale:1.3}),self(plants,'Natural potential',{below:true,scale:1.1,delay:550}),self(text,'Request offered',{scale:.7,delay:900})]);
add('prismatic-sphere','Seven-layered sphere',[field('bubble.001.001.complete.blue','Prismatic shell',{opacity:.5}),...['#ff4141','#ffa74a','#f2e965','#77ca69','#67b3ea','#6864c8','#b979d4'].map((tint,i)=>field('bubble.001.001.complete.blue','Prismatic layer',{scale:1-i*.035,tint,opacity:.25,delay:350+i*100}))],{delivery:'burst',previewArea:{type:'burst',value:10},nativeArea:true});
add('procyal-philosophy','Helpful procyal visage',[body(eyes,'Procyal visage symbol',{offsetX:.75,offsetY:-.4,scale:.65}),body(text,'Helpful advice',{offsetX:.8,scale:.6,delay:650})]);
add('project-image','Projected self',[image('Illusory self',{subject:'source',copies:1,offsetX:1.2,opacity:.75}),self(shimmer,'Image projects',{offsetX:1.2,scale:1.1,delay:350})]);
add('proliferating-eyes','Invisible eye sensor',[body(eye,'Sensor implanted',{scale:.45,opacity:.5}),body('energy_strands.02.marker.bluepurple','Sensor connection',{scale:.75,opacity:.35,delay:650})]);
add('prophets-luck','Saving throw prophecy',[self(text,'Outcome prophesied',{scale:.65,offsetY:-.35}),body(dice,'Unresolved fortune',{scale:.6,delay:600})]);
add('propulsive-breeze','Wind at ally back',[body('wind_lines.01.01.white','Propelling current',{rotation:90,scale:1.15}),body('swirling_feathers.outburst.01.textured','Current continues',{scale:.75,delay:500})]);
add('protective-wards','Ring of protective glyphs',[field(ward,'Protective glyph ring'),field(shield,'Ally defense',{scale:.3,delay:650})],{nativeArea:true});
add('protector-tree','Protective tree growth',[self(plants,'Tree grows',{below:true,scale:1.05}),self(vines,'Branches form',{scale:1.2,delay:500}),self(shield,'Protection prepared',{scale:.5,delay:900})]);
add('protectors-sacrifice','Ally harm redirected',[body(heart,'Ally burden',{scale:.5}),link(tether,'Burden reaches caster',{travelOrigin:'target',scale:.5,delay:400}),self(heart,'Caster accepts harm',{scale:.6,delay:850})],{pattern:'tetherConnection'});
add('protectors-sphere','Protective emanation',[field('bubble.001.001.complete.blue','Protective sphere',{opacity:.45}),field(shield,'Shared resistance',{scale:.3,delay:650})],{nativeArea:true});
add('prying-survey','Eight scouting eyes',[self(eyes,'Eight eyes prepared',{scale:.85,offsetY:-.35}),field(pulse,'Eyes survey area',{opacity:.2,delay:500}),field(eyes,'Eye sensors',{scale:.35,opacity:.45,delay:850})],{nativeArea:true});
add('psychic-outburst','Psychic energy release',[self(eye,'Mental energy filters',{scale:.65,offsetY:-.3}),field(voidField,'Psychic outburst',{delay:450}),field(particles,'Psychic energy outward',{opacity:.55,delay:850})],{nativeArea:true,castingOnly:false});
add('pulse-of-civilization','Settlement information',[self(pulse,'Settlement pulse',{scale:1.5,opacity:.35}),self(text,'Settlement names known',{offsetY:-.35,scale:.8,delay:650})]);
add('puppet-strings','Ethereal control threads',[self(strands,'Fingertip threads',{scale:.7,offsetX:.3}),link(tether,'Threads reach limbs',{scale:.45,delay:300}),body(strands,'Body threads',{delay:650,opacity:.7})],{pattern:'tetherConnection'});
add('purging-toxins','Poison purge',[body(poison,'Measured poison dose',{scale:.5}),body(inward,'Toxins drawn out',{scale:.9,delay:550}),body(heart,'Cure attempted',{scale:.4,delay:900})],{castingOnly:false});
add('purify-soul-path','Soul reconciliation',[self(eye,'Inward contemplation',{scale:.55,offsetY:-.35}),self(text,'Past actions examined',{scale:.75,delay:500}),self('ward.star.yellow.01','Soul reconciliation petition',{scale:.85,delay:950})]);
add('purify-tanglebriar','Forest purification invocation',[self(plants,'Ancient forest spirits',{below:true,scale:1.1}),self(leaves,'Elven legacy petition',{scale:1.25,delay:500}),self('ward.star.yellow.01','Blight cleansing petition',{scale:.8,delay:950})]);
add('purifying-veil','Holy water droplets',[body(splash,'Fine water droplets',{scale:1.15,opacity:.6}),body('ward.star.yellow.01','Holy veil',{scale:.85,opacity:.5,delay:550})]);
add('pushing-gust','Buffeting wind',[link('gust_of_wind.veryfast','Directed gust',{scale:.75}),body('wind_lines.01.01.white','Wind buffets',{scale:1.1,delay:550})],{pattern:'tetherConnection'});
add('putrefy-food-and-drink','Food spoilage',[body('liquid.blob.blue','Food or drink focus',{scale:.65,tint:'#81775c'}),body(poison,'Putrefaction',{scale:.45,delay:600}),body('fumes.04.complete.grey','Spoiled vapors',{scale:.65,opacity:.35,delay:950})]);
add('pyrotechnics','Fire altered',[body(inward,'Fire drawn down',{scale:.85}),body(signs,'Fireworks or smoke choice',{scale:.55,offsetY:-.35,delay:600})]);
add('qi-blast','Qi cone blast',[self(strands,'Qi concentrates',{scale:.8}),fan(voidField,'Qi force fan',{fanCount:7,delay:400,scale:.5})],{pattern:'coneObjectFan',nativeArea:true,castingOnly:false});
add('quantic-dampening','Elemental control field',[field('energy_field.01.blue','Elemental control',{opacity:.5}),field(shield,'Damage mitigation potential',{scale:.3,delay:650})],{nativeArea:true});
add('quench','Supersaturated vapor',[field('fumes.steam','Water vapor saturates',{opacity:.65}),field(splash,'Vapor quenches',{opacity:.35,delay:650})],{nativeArea:true,castingOnly:false});
add('quicken-time','Swift temporal field',[field('energy_strands.02.marker.bluepurple','Time stretches',{playbackRate:1.25}),field(shimmer,'Uneven temporal boundary',{opacity:.45,delay:600})],{nativeArea:true});
add('raga-of-remembrance','Remembrance raga invocation',[self(text,'Occult ground symbols',{below:true,scale:1.1}),self('fumes.steam','Incense offering',{scale:.6,offsetY:-.3,delay:300}),self(notes,'Ritual drone',{scale:.75,delay:650}),self('spirit_guardians.blueyellow.ring','Fallen defenders petition',{opacity:.4,delay:1000})]);
add('raise-runelord','Runelord illusion invocation',[body(rune,'Runelord remnant focus',{scale:.65}),body('sleep.cloud.01.pink','Dreamlands energies invoked',{opacity:.45,delay:500}),body(shimmer,'Physical illusion petition',{scale:1.2,opacity:.5,delay:950})]);
add('rally-point','Marked rally square',[field('energy_strands.02.marker.bluepurple','Rally point marked',{scale:.95}),field(ward,'Return mark',{scale:.55,delay:650})],{nativeArea:true});
add('rallying-banner','Illusory banner celebration',[body(signs,'Banner symbol',{scale:1.1,offsetY:-1.2}),body('firework.01','Celebratory fireworks',{scale:1.4,offsetY:-.85,delay:500}),body(sound,'Cheering crowd',{scale:1.1,delay:850})]);
add('ransack-the-night','Night shroud invocation',[self('ground_cracks.01.orange','Troughs prepared',{below:true}),self('liquid.splash.blue','Salt and citrus offering',{below:true,scale:.6,delay:450}),self(mist,'Night miasma petition',{opacity:.5,delay:900})]);
add('ravenous-portal','Door mimic ward',[body(ward,'Door ward placed',{scale:.85}),body('energy_strands.02.marker.bluepurple','Trigger held',{scale:1.1,opacity:.45,delay:650})]);
add('ravenous-reanimation','Ravener invocation',[self(fire,'Treasures charred',{below:true,scale:.85}),self('aura_themed.01.inward.complete.metal.01.grey','Melted offering',{below:true,scale:.9,delay:450}),self(skull,'Necromancy invoked',{scale:.65,delay:900})]);
add('reapers-lantern','Ghostly lantern',[self('dancing_light.blueteal','Ghostly lantern',{scale:.55,offsetX:.55,offsetY:-.3}),self('arcane_hand.blue','Ephemeral hand',{scale:.5,offsetX:.55,offsetY:-.45,delay:400}),field('template_circle.aura.01.complete.small.bluepurple','Lantern light',{opacity:.35,delay:650})],{nativeArea:true});
add('reblooded','Undead blood circulation',[body(heart,'Stopped heart stirs',{scale:.55,offsetY:.05}),body('liquid.splash02.red','Blood courses',{maskToken:true,scale:.85,delay:550})]);
add('recall-legacy','Ancestral knowledge link',[link(tether,'Legacy connection',{scale:.45}),body(text,'Shared legacy recalled',{scale:.75,offsetY:-.35,delay:500}),body(eye,'Ancestral insight',{scale:.45,offsetY:-.5,delay:850})],{pattern:'tetherConnection'});
add('recall-past-life','Past life ritual',[body(signs,'Body sigils',{maskToken:true}),body(water,'Herbed wine offering',{scale:.55,delay:500}),body(petals,'Orchid bed petition',{below:true,delay:850}),body(eye,'Past life contact',{scale:.5,offsetY:-.35,delay:1150})]);
add('redact','Writing obscured',[body(text,'Named text identified',{scale:.75}),body(mist,'Name blurred',{scale:.7,opacity:.65,delay:550}),body('icon.mute.dark_red','Reference obscured',{scale:.45,delay:850})]);
add('reflected-beauty','Desired appearance',[self(shimmer,'Reflected disguise',{maskToken:true}),self(heart,'Desired appearance',{scale:.5,offsetY:-.35,delay:600}),self(eye,'Subject reflection',{scale:.45,offsetY:-.55,delay:850})]);
add('regale-the-lost-ones','Opera for spirits',[self(notes,'Opera performed',{scale:.85,offsetY:-.35}),self(sound,'Spirit audience addressed',{scale:1.25,delay:500}),self('spirit_guardians.blueyellow.ring','Lost ones petition',{scale:1.15,opacity:.4,delay:950})]);
add('reincarnate','Soul incarnation petition',[body('spirit_guardians.blueyellow.ring','Departed soul called',{opacity:.45}),body('energy_strands.02.marker.bluepurple','New body petition',{scale:1.2,delay:550}),body(heart,'Return to life requested',{scale:.5,delay:1000})]);

const radialSlots=['hit','aura','cast','area'];
// A projectile fan alone does not show the native cone; add its footprint.
for(const profile of profiles)if(profile.nodes.some(n=>n.kind==='fan')&&!profile.nodes.some(n=>n.kind==='field'))
  profile.nodes.push(field('detect_magic.cone','Cone footprint',{opacity:.4,fadeOut:300}));
const plans=new Map();
export const GAP_B_MOTIFS={};
export const GAP_B_DESIGNS={};
for(const profile of profiles){
  const motif=`gapB_${profile.slug.replace(/-legacy$/,'').replace(/-/g,'_')}`;
  const roots={},assigned=new Map();
  const nodes=profile.nodes.map(node=>{
    if(!node.root)return node;
    const preferred=['link','object','fan'].includes(node.kind)?'bolt':node.kind==='field'?'area':null;
    const lookup=`${preferred??'radial'}:${node.root}`;
    let slot=assigned.get(lookup);
    if(!slot){
      slot=preferred&&!roots[preferred]?preferred:radialSlots.find(candidate=>!roots[candidate]);
      if(!slot)throw Error(`Too many asset roots: ${profile.slug}`);
      roots[slot]=node.root;assigned.set(lookup,slot);
    }
    return {...node,slot};
  });
  const pattern=profile.pattern??(nodes.some(n=>n.kind==='link')?'tetherConnection':nodes.some(n=>n.kind==='object')?'object':'gapBComposition');
  GAP_B_MOTIFS[motif]={label:profile.label,pattern,...roots,symbolic:profile.symbolic,castingOnly:profile.castingOnly,
    ...(profile.nativeArea?{nativeArea:true}:{}),...(profile.delivery?{delivery:profile.delivery}:{}),
    ...(profile.areaLayout?{areaLayout:profile.areaLayout}:{}),...(profile.previewArea?{previewArea:profile.previewArea}:{}),
    assetIntent:profile.label};
  GAP_B_DESIGNS[profile.slug.replace(/-legacy$/,'')]=[motif,''];
  plans.set(motif,{...profile,nodes});
}

export function gapBLayers(spell,{fx,copy,track,subject}){
  const plan=plans.get(spell.design.motif);
  if(!plan)return null;
  return plan.nodes.map(node=>{
    const {kind,root,slot,label,delay=0,subject:who=subject,alphaOut,color,...rest}=node;
    const speed=Math.max(.1,rest.playbackRate??1);
    const duration=Math.max(3400,(spell.design.mediaTiming?.[slot]?.duration??0)/speed+200);
    const extra={scale:1,opacity:.8,fadeIn:350,fadeOut:500,subject:who,...rest,
      ...(color?{tint:color}:{}),...((rest.tint||color)?{tintEnabled:true,colorize:true}:{}),
      ...(alphaOut?{tracks:[track('alpha',.7,0,Math.max(2200,duration-500))]}:{})};
    if(kind==='image')return copy(label,delay,duration,extra);
    if(kind==='field')return fx('template',slot,label,delay,duration,{below:true,scale:1,...extra});
    if(kind==='link')return fx('travel',slot,label,delay,duration,{scale:.6,fadeIn:0,fadeOut:200,...extra});
    if(kind==='object')return fx('projectile',slot,label,delay,duration,{scale:.6,fadeIn:0,moveDelay:100,moveEase:'easeOutCubic',...extra});
    if(kind==='fan')return fx('projectile',slot,label,delay,duration,{travelDestination:'area',areaLayout:'fan',fanCount:7,scale:.5,fadeIn:0,moveDelay:100,moveEase:'easeOutCubic',...extra});
    return fx(who==='targets'?'impact':'cast',slot,label,delay,duration,extra);
  });
}

// Machine-readable semantic fields; native prose is deliberately excluded.
export function gapBReviewProfile(slug){
  const tuple=GAP_B_DESIGNS[slug.replace(/-legacy$/,'')];
  if(!tuple)return null;
  const profile=plans.get(tuple[0]);
  return {motif:tuple[0],symbolic:profile.symbolic,castingOnly:profile.castingOnly,
    descriptionSource:profile.descriptionSource??'value',
    delivery:profile.delivery??null,previewArea:profile.previewArea??null,
    stageRoles:profile.nodes.map(({kind,slot,root,label,subject:who,delay,...options})=>({kind,slot:slot??null,root:root??null,
      subject:who??'native',areaLayout:options.areaLayout??(kind==='fan'?'fan':null),options}))};
}
